CREATE TABLE FININT.WSC_AHCS_RECON_DEBUG_T
(
  DEBUG_ID          NUMBER                      NOT NULL,
  LOCATION          VARCHAR2(400 BYTE),
  MESSAGE           VARCHAR2(1000 BYTE),
  CREATED_BY        NUMBER(15),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  ATTRIBUTE1        VARCHAR2(100 BYTE),
  ATTRIBUTE2        VARCHAR2(100 BYTE),
  ATTRIBUTE3        VARCHAR2(100 BYTE),
  ATTRIBUTE4        VARCHAR2(100 BYTE),
  ATTRIBUTE5        VARCHAR2(100 BYTE),
  ATTRIBUTE6        VARCHAR2(100 BYTE),
  ATTRIBUTE7        VARCHAR2(100 BYTE),
  ATTRIBUTE8        VARCHAR2(100 BYTE),
  ATTRIBUTE9        VARCHAR2(100 BYTE),
  ATTRIBUTE10       VARCHAR2(100 BYTE)
);

GRANT SELECT ON FININT.WSC_AHCS_RECON_DEBUG_T TO FININT_RO;