REM INSERTING into WSC_AHCS_REFRESH_T
SET DEFINE OFF;
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (to_timestamp(SYSDATE-60,'DD-MON-RR HH.MI.SSXFF AM'),'ORACLE_LSI_EXCHANGE',SYSDATE,'Integration Program',null);
commit;
