ALTER TABLE "FININT"."WSC_AHCS_DASHBOARD2_STAGE_T" 
ADD "SOURCE_SYSTEM" VARCHAR2(100 BYTE);

ALTER TABLE "FININT"."WSC_AHCS_DASHBOARD2_T" 
ADD "SOURCE_SYSTEM" VARCHAR2(100 BYTE);

alter table WSC_AHCS_DASHBOARD2_STAGE_T modify(CREATE_ACC_STATUS varchar2(100));
alter table WSC_AHCS_DASHBOARD2_T  modify(CREATE_ACC_STATUS varchar2(100));