 CREATE TABLE "FININT"."WSC_AHCS_RECON_REP_TEMP_T" 
   (	"FILE_NAME" VARCHAR2(100 BYTE), 
	"TRX_NUMBER" VARCHAR2(50 BYTE), 
	"JOB_ID" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(15 BYTE), 
	"COMPLETION_DATE" TIMESTAMP (6)
   );

