SET DEFINE OFF;
@WSC_EXT011_TABLE.sql
@WSC_EXT011_TABLE_TYPE.sql
@WSC_EXT011_SEQUENCE.sql
@WSC_EXT011_RECON_RECORDS_PKG.sql
@WSC_EXT011_RECON_RECORDS_PKG_BODY.sql
@Insert_WSC_AHCS_REFRESH_T.sql
commit;