SET ECHO ON;
SET DEFINE OFF;

PROMPT "EXECUTING WSC_AHCS_DASHBOARD2_T.sql";
@WSC_AHCS_DASHBOARD2_T.sql



PROMPT "EXECUTING WSC_AHCS_DASHBOARD2_STAGE_T.sql";
@WSC_AHCS_DASHBOARD2_STAGE_T.sql;



PROMPT "EXECUTING WSC_AHCS_DASHBOARD2_V.sql";
@WSC_AHCS_DASHBOARD2_V.sql


