SET DEFINE OFF;
Insert into WSC_AHCS_INT_AHCS_SOURCES_LKP_T (ID,LEAGACY_APPLICATION_NAME,AHCS_APPLICATION_NAME) values (101,'Oracle LSI','ORACLE LSI');
Insert into WSC_AHCS_INT_AHCS_SOURCES_LKP_T (ID,LEAGACY_APPLICATION_NAME,AHCS_APPLICATION_NAME) values (102,'CLOUDPAY','CloudPay');
commit;