--------------------------------------------------------
--  File created - Monday-September-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Index WSC_AHCS_AR_TXN_HEADER_BATCH_ID_I, WSC_AHCS_AR_TXN_HEADER_LEG_AE_HEADER_ID_I
--------------------------------------------------------


CREATE INDEX "FININT"."WSC_AHCS_AR_TXN_HEADER_BATCH_ID_I" ON "FININT"."WSC_AHCS_AR_TXN_HEADER_T" ("BATCH_ID") ;
CREATE INDEX "FININT"."WSC_AHCS_AR_TXN_HEADER_LEG_AE_HEADER_ID_I" ON "FININT"."WSC_AHCS_AR_TXN_HEADER_T" ("LEG_AE_HEADER_ID") ;

ALTER INDEX WSC_AHCS_AR_TXN_HEADER_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_AR_TXN_HEADER_LEG_AE_HEADER_ID_I REBUILD COMPUTE STATISTICS;



--------------------------------------------------------
--  File created - Monday-September-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Index WSC_AHCS_AR_TXN_LINE_BATCH_ID_I, WSC_AHCS_AR_TXN_LINE_HEADER_ID_I,
--                 WSC_AHCS_AR_TXN_LINE_LEG_AE_HEADER_ID_I, WSC_AHCS_AR_TXN_LINE_LEG_COA_I
--------------------------------------------------------

  
CREATE INDEX "FININT"."WSC_AHCS_AR_TXN_LINE_BATCH_ID_I" ON "FININT"."WSC_AHCS_AR_TXN_LINE_T" ("BATCH_ID"); 
CREATE INDEX "FININT"."WSC_AHCS_AR_TXN_LINE_HEADER_ID_I" ON "FININT"."WSC_AHCS_AR_TXN_LINE_T" ("HEADER_ID") ;
CREATE INDEX "FININT"."WSC_AHCS_AR_TXN_LINE_LEG_COA_I" ON "FININT"."WSC_AHCS_AR_TXN_LINE_T" ("LEG_COA") ;
CREATE INDEX "FININT"."WSC_AHCS_AR_TXN_LINE_LEG_AE_HEADER_ID_I" ON "FININT"."WSC_AHCS_AR_TXN_LINE_T" ("LEG_AE_HEADER_ID") ;

ALTER INDEX WSC_AHCS_AR_TXN_LINE_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_AR_TXN_LINE_HEADER_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_AR_TXN_LINE_LEG_AE_HEADER_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_AR_TXN_LINE_LEG_COA_I REBUILD COMPUTE STATISTICS;

commit;