--+========================================================================|
--| RICE_ID             : INT122 - Daily GL journal feed from ERP POC to AHCS
--| Module/Object Name  : WSC_POC_TABLE.sql
--|
--| Description         : Object to contain POC Table creation Script
--|
--| Creation Date       : 06-SEPT-2021
--|
--| Author              : Syed Zafer Ali
--|
--+========================================================================|
--| Modification History
--+========================================================================|
--| Date			Who					Version	    Change Description
--| -----------------------------------------------------------------------|
--| 06-SEPT-2021	Syed Zafer Ali   	Draft	    Initial draft version  |
--+========================================================================|

-- DROP TABLE "FININT"."WSC_AHCS_POC_TXN_HEADER_T" ;
-- /

-- DROP TABLE "FININT"."WSC_AHCS_POC_TXN_LINE_T";
-- /

  CREATE TABLE "FININT"."WSC_AHCS_POC_TXN_HEADER_T" 
   (	"HEADER_ID" NUMBER, 
	"BATCH_ID" NUMBER, 
	"TRANSACTION_DATE" DATE, 
	"TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"LEDGER_NAME" VARCHAR2(100 BYTE), 
	"JE_SOURCE" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM" VARCHAR2(100 BYTE), 
	"JE_AMOUNT" NUMBER, 
	"JE_HEADER_ID" NUMBER, 
	"GL_DATE" DATE, 
	"JE_HEADER_DESC" VARCHAR2(1000 BYTE), 
	"LEG_LED_NAME" VARCHAR2(100 BYTE), 
	"JE_BATCH_NAME" VARCHAR2(100 BYTE), 
	"JE_CATEGORY" VARCHAR2(100 BYTE), 
	"FILE_NAME" VARCHAR2(100 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(100 BYTE),  
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE),
	"ATTRIBUTE1" VARCHAR2(100 BYTE), 
	"ATTRIBUTE2" VARCHAR2(100 BYTE), 
	"ATTRIBUTE3" VARCHAR2(100 BYTE), 
	"ATTRIBUTE4" VARCHAR2(100 BYTE), 
	"ATTRIBUTE5" VARCHAR2(100 BYTE), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" NUMBER, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" DATE,
	 CONSTRAINT "WSC_AHCS_POC_TXN_HEADER_T_PK" PRIMARY KEY ("HEADER_ID"));
 
  CREATE TABLE "FININT"."WSC_AHCS_POC_TXN_LINE_T" 
   (	"LINE_ID" NUMBER,
   	"HEADER_ID" NUMBER, 
	"JE_HEADER_ID" NUMBER, 
	"DEFAULT_AMOUNT" NUMBER, 
	"ACC_AMT" NUMBER, 
	"DEFAULT_CURRENCY" VARCHAR2(100 BYTE), 
	"ACC_CURRENCY" VARCHAR2(100 BYTE), 
	"LEG_SEG1" VARCHAR2(100 BYTE), 
	"LEG_SEG2" VARCHAR2(100 BYTE), 
	"LEG_SEG3" VARCHAR2(100 BYTE), 
	"LEG_SEG4" VARCHAR2(100 BYTE), 
	"LEG_SEG5" VARCHAR2(100 BYTE), 
	"LEG_SEG6" VARCHAR2(100 BYTE), 
	"LEG_SEG7" VARCHAR2(100 BYTE), 
	"DR_CR_FLAG" VARCHAR2(100 BYTE), 
	"JE_LINE_NBR" NUMBER, 
	"JE_LINE_DESC" LONG, 
	"FX_RATE" NUMBER, 
	"TARGET_COA" VARCHAR2(100 BYTE), 
	"BATCH_ID" NUMBER, 
	"TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"LEG_COA" VARCHAR2(100 BYTE), 
	"GL_LEGAL_ENTITY" VARCHAR2(100 BYTE), 
	"GL_ACCT" VARCHAR2(100 BYTE), 
	"GL_OPER_GRP" VARCHAR2(100 BYTE), 
	"GL_DEPT" VARCHAR2(100 BYTE), 
	"GL_SITE" VARCHAR2(100 BYTE), 
	"GL_IC" VARCHAR2(100 BYTE), 
	"GL_PROJECTS" VARCHAR2(100 BYTE), 
	"GL_FUT_1" VARCHAR2(100 BYTE), 
	"GL_FUT_2" VARCHAR2(1000 BYTE),
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 	
	"ATTRIBUTE1" VARCHAR2(100 BYTE), 
	"ATTRIBUTE2" VARCHAR2(100 BYTE), 
	"ATTRIBUTE3" VARCHAR2(100 BYTE), 
	"ATTRIBUTE4" VARCHAR2(100 BYTE), 
	"ATTRIBUTE5" VARCHAR2(100 BYTE), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" NUMBER, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" DATE, 
	 CONSTRAINT "WSC_AHCS_POC_TXN_LINE_T_PK" PRIMARY KEY ("LINE_ID"));