set define off;
Insert into finint.wsc_gl_coa_mapping_rules_t (RULE_ID,COA_MAP_ID,RULE_NAME,DESCRIPTION,RULE_PRIORITY,SOURCE_SYSTEM,TARGET_SYSTEM,SOURCE_SEGMENT1,SOURCE_SEGMENT2,SOURCE_SEGMENT3,SOURCE_SEGMENT4,SOURCE_SEGMENT5,SOURCE_SEGMENT6,SOURCE_SEGMENT7,SOURCE_SEGMENT8,SOURCE_SEGMENT9,SOURCE_SEGMENT10,TARGET_SEGMENT,DEFAULT_VALUE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_LOGIN,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10)
values (70,3,'Central COA - Department - Based on Central Branch & Account',null,1,'CENTRAL','Oracle ERP Cloud','Y','Y',NULL,null,null,null,null,null,null,null,'segment4',null,'FIN_INT',SYSDATE,'FIN_INT',SYSDATE,null,null,null,null,null,null,null,null,null,null,null);

commit;
/