SET ECHO ON;
SET DEFINE OFF;

PROMPT "EXECUTING WSC_GL_COA_INSERT_T.sql";
@WSC_GL_COA_INSERT_T.sql;

PROMPT "EXECUTING WSC_GL_COA_MAPPING_PKG.sql";
@WSC_GL_COA_MAPPING_PKG.sql;

PROMPT "EXECUTING WSC_GL_COA_MAPPING_PKG_BODY.sql";
@WSC_GL_COA_MAPPING_PKG_BODY.sql;

COMMIT;



