SET ECHO ON;
SET DEFINE OFF;


PROMPT "EXECUTING WSC_EXTENSION_013_SEQUENCE.sql";
@WSC_EXTENSION_013_SEQUENCE.sql

PROMPT "EXECUTING WSC_EXTENSION_013_TABLE.sql";
@WSC_EXTENSION_013_TABLE.sql;

PROMPT "EXECUTING WSC_EXTENSION_013_INDEX.sql";
@WSC_EXTENSION_013_INDEX.sql

PROMPT "EXECUTING WSC_EXTENSION_013_TRIGGER.sql";
@WSC_EXTENSION_013_TRIGGER.sql

PROMPT "EXECUTING WSC_EXTENSION_013_PROCEDURE.sql";
@WSC_EXTENSION_013_PROCEDURE.sql


PROMPT "EXECUTING WSC_USER_COA_TRANSFORMATION_PKG.sql";
@WSC_USER_COA_TRANSFORMATION_PKG.sql

PROMPT "EXECUTING WSC_USER_COA_TRANSFORMATION_PKG_BODY.sql";
@WSC_USER_COA_TRANSFORMATION_PKG_BODY.sql

COMMIT;