drop table  "FININT"."WSC_AHCS_MFAP_TXN_HEADER_T";
drop table  "FININT"."WSC_AHCS_MFAP_TXN_LINE_T";
drop table  "FININT"."WSC_AHCS_MFAP_TXN_TMP_T";
DROP SEQUENCE "FININT"."WSC_MFAP_HEADER_T_S1"; 
DROP SEQUENCE "FININT"."WSC_MFAP_LINE_S1"; 
DROP SEQUENCE "FININT"."WSC_TW_TMP_LINE_NBR_S1"; 
DROP TYPE WSC_MFAP_TMP_T_TYPE_TABLE;
DROP TYPE WSC_MFAP_TMP_T_TYPE;