CREATE INDEX "FININT"."WSC_AHCS_MFAP_TXN_HEADER_BATCH_ID_I" ON "FININT"."WSC_AHCS_MFAP_TXN_HEADER_T" ("BATCH_ID");
CREATE INDEX "FININT"."WSC_AHCS_MFAP_TXN_HEADER_HDR_SEQ_NBR_I" ON "FININT"."WSC_AHCS_MFAP_TXN_HEADER_T" ("HDR_SEQ_NBR");

ALTER INDEX WSC_AHCS_MFAP_TXN_HEADER_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_MFAP_TXN_HEADER_HDR_SEQ_NBR_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_MFAP_TXN_HEADER_T_PK REBUILD COMPUTE STATISTICS;


CREATE INDEX "FININT"."WSC_AHCS_MFAP_TXN_LINE_HEADER_ID_I" ON "FININT"."WSC_AHCS_MFAP_TXN_LINE_T" ("HEADER_ID") ;
CREATE INDEX "FININT"."WSC_AHCS_MFAP_TXN_LINE_LEG_COA_I" ON "FININT"."WSC_AHCS_MFAP_TXN_LINE_T" ("LEG_COA")  ;
CREATE INDEX "FININT"."WSC_AHCS_MFAP_TXN_LINE_BATCH_ID_I" ON "FININT"."WSC_AHCS_MFAP_TXN_LINE_T" ("BATCH_ID") ;
CREATE INDEX "FININT"."WSC_AHCS_MFAP_TXN_LINE_HDR_SEQ_NBR_I" ON "FININT"."WSC_AHCS_MFAP_TXN_LINE_T" ("HDR_SEQ_NBR") ;

ALTER INDEX WSC_AHCS_MFAP_TXN_LINE_HEADER_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_MFAP_TXN_LINE_LEG_COA_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_MFAP_TXN_LINE_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_MFAP_TXN_LINE_HDR_SEQ_NBR_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_MFAP_TXN_LINE_T_PK REBUILD COMPUTE STATISTICS;


CREATE INDEX "FININT"."WSC_AHCS_MFAP_TXN_TMP_BATCH_ID_I" ON "FININT"."WSC_AHCS_MFAP_TXN_TMP_T" ("BATCH_ID")  ;
CREATE INDEX "FININT"."WSC_AHCS_MFAP_TMP_T_REG_I" ON "FININT"."WSC_AHCS_MFAP_TXN_TMP_T" ( REGEXP_SUBSTR ("DATA_STRING",'([^|]*)(\||$)',1,1,NULL,1))  ;

ALTER INDEX WSC_AHCS_MFAP_TXN_TMP_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_MFAP_TMP_T_REG_I REBUILD COMPUTE STATISTICS;

commit;