SET ECHO ON;
SET DEFINE OFF;

@01_WSC_DGTL_PLS_DEBUG_SEQ.sql;
@02_WSC_DGTL_PLS_DEBUG_T.sql;
@03_WSC_DGTL_PLS_GRANTS.sql;
@04_WSC_DGTL_PLS_PURGING_SPEC.sql;
@05_WSC_DGTL_PLS_PURGING_BODY.sql;

COMMIT;
