  CREATE TABLE "FININT"."WSC_AHCS_DASHBOARD2_STAGE_T" 
   (	"APPLICATION" VARCHAR2(200 BYTE), 
	"ACCOUNTING_PERIOD" VARCHAR2(15 BYTE), 
	"INTERFACE_PROC_STATUS" VARCHAR2(200 BYTE), 
	"CREATE_ACC_STATUS" VARCHAR2(15 BYTE), 
	"TOTAL_CR" NUMBER, 
	"TOTAL_DR" NUMBER, 
	"NUM_ROWS" NUMBER, 
	"DUMMY" VARCHAR2(4 BYTE), 
	"DUMMY4" VARCHAR2(4 BYTE)
  );