create or replace TYPE WSC_MFAR_TMP_T_TYPE FORCE AS OBJECT (
	"BATCH_ID" NUMBER, 
	"RICE_ID" VARCHAR2(20),
	"DATA_STRING" VARCHAR2(4000), 
    CONSTRUCTOR FUNCTION WSC_MFAR_TMP_T_TYPE RETURN SELF AS RESULT
);
/
create or replace TYPE BODY WSC_MFAR_TMP_T_TYPE AS
    CONSTRUCTOR FUNCTION WSC_MFAR_TMP_T_TYPE RETURN SELF AS RESULT AS
    BEGIN
        return;
    END;

END;
/
create or replace TYPE WSC_MFAR_TMP_T_TYPE_TABLE FORCE AS
    TABLE OF WSC_MFAR_TMP_T_TYPE;
/
