SET ECHO ON;

PROMPT "EXECUTING WSC_AXE_INT216_TABLE.sql";
@WSC_AXE_INT216_TABLE.sql;

PROMPT "EXECUTING WSC_AXE_INT216_INDEXES.sql";
@WSC_AXE_INT216_INDEXES.sql

PROMPT "EXECUTING WSC_AXE_INT216_SEQUENCES.sql";
@WSC_AXE_INT216_SEQUENCES.sql

PROMPT "EXECUTING WSC_AXE_INT216_TABLE_TYPES.sql";
@WSC_AXE_INT216_TABLE_TYPES.sql;

PROMPT "EXECUTING WSC_AXE_INT216_PKG.sql";
@WSC_AXE_INT216_PKG.sql

PROMPT "EXECUTING WSC_AXE_INT216_PKG_BODY.sql";
@WSC_AXE_INT216_PKG_BODY.sql

PROMPT "EXECUTING WSC_AXE_INT216_VALIDATION_TRANSFORMATION_PKG.sql";
@WSC_AXE_INT216_VALIDATION_TRANSFORMATION_PKG.sql

PROMPT "EXECUTING WSC_AXE_INT216_VALIDATION_TRANSFORMATION_PKG_BODY.sql";
@WSC_AXE_INT216_VALIDATION_TRANSFORMATION_PKG_BODY.sql

COMMIT;
