
  CREATE UNIQUE INDEX "FININT"."WSC_AHCS_LSI_EXCHANGE_RATE_T_PK" ON "FININT"."WSC_AHCS_LSI_EXCHANGE_RATE_T" ("FROM_CURRENCY", "TO_CURRENCY", "CONVERSION_DATE", "CONVERSION_RATE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "FININT"."WSC_AHCS_LSI_LOOKUP_T_PK" ON "FININT"."WSC_AHCS_LSI_LOOKUP_T" ("LOOKUP_TYPE", "LOOKUP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

