create or replace TYPE  WES_AHCS_LSI_JOURNAL_T_TYPE FORCE AS OBJECT 
(
   "LEDGER_NAME" VARCHAR2(100 BYTE), 
	"LEGAL_ENTITY_NAME" VARCHAR2(240 BYTE), 
	"GL_BATCH_ID" NUMBER, 
	"GL_BATCH_NAME" VARCHAR2(100 BYTE), 
	"GL_JOURNAL_ID" NUMBER, 
	"JOURNAL_HEADER_NAME" VARCHAR2(100 BYTE), 
	"JOURNAL_LINE_NUMBER" NUMBER, 
	"GL_POSTED_DATE" TIMESTAMP, 
	"EXCHANGE_RATE_DATE" DATE, 
	"EXCHANGE_RATE" NUMBER, 
	"EXCHANGE_RATE_TYPE" VARCHAR2(100 BYTE), 
	"SEGMENT1" VARCHAR2(20 BYTE), 
	"SEGMENT2" VARCHAR2(20 BYTE), 
	"SEGMENT3" VARCHAR2(20 BYTE), 
	"SEGMENT4" VARCHAR2(20 BYTE), 
	"SEGMENT5" VARCHAR2(20 BYTE), 
	"SEGMENT6" VARCHAR2(20 BYTE), 
	"SEGMENT7" VARCHAR2(20 BYTE), 
	"SEGMENT8" VARCHAR2(20 BYTE), 
	"SEGMENT9" VARCHAR2(20 BYTE), 
	"JOURNAL_ACCOUNTING_SEQUENCE" NUMBER, 
	"RUNNING_TOTAL_DR" NUMBER, 
	"RUNNING_TOTAL_CR" NUMBER, 
	"RUNNING_TOTAL_ACCOUNTED_DR" NUMBER, 
	"RUNNING_TOTAL_ACCOUNTED_CR" NUMBER, 
	"INTERCOMPANY_BATCH_NUMBER" NUMBER, 
	"PROVIDER_LEGAL_ENTITY" VARCHAR2(240 BYTE), 
	"INTERCOMPANY_TRANSACTION_TYPE" VARCHAR2(100 BYTE), 
	"LEDGER_ID" NUMBER, 
	"ENTERED_CURRENCY_CODE" VARCHAR2(10 BYTE), 
    "FUNCTIONAL_CURRENCY_CODE" VARCHAR2(10 BYTE),
	"INTERCOMPANY_TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"JE_SOURCE" VARCHAR2(80 BYTE), 
	"ACTUAL_FLAG" VARCHAR2(20 BYTE),
    "FILE_NAME" VARCHAR2(100 BYTE),
    "STATUS" VARCHAR2(100 BYTE),
    "PARTY_TYPE_FLAG" VARCHAR2(10)
);
/

create or replace TYPE WES_AHCS_LSI_JOURNAL_T_TYPE_TABLE 
AS TABLE OF WES_AHCS_LSI_JOURNAL_T_TYPE;
/

create or replace TYPE          "WSC_AHCS_LSI_CM_VAL_T_TYPE" FORCE AS OBJECT
( 
INVOICE_NUM VARCHAR2(100),
VENDOR_NAME VARCHAR2(360),
VENDOR_SITE_CODE VARCHAR2(240),
BU VARCHAR2(100),
APPROVAL_STATUS VARCHAR2(100) ,
REQUEST_ID VARCHAR2(100)
);
/

create or replace TYPE          "WSC_AHCS_LSI_CM_VAL_T_TYPE_TABLE" 
AS TABLE OF  wsc_ahcs_lsi_cm_val_t_TYPE;
/

create or replace TYPE WSC_AHCS_LSI_EXCHANGE_RATE_T_TYPE FORCE AS OBJECT 
( 
FROM_CURRENCY	VARCHAR2(10 BYTE),
TO_CURRENCY	VARCHAR2(10 BYTE),
CONVERSION_DATE	VARCHAR2(10 BYTE),
CONVERSION_RATE_TYPE	VARCHAR2(20 BYTE),
CONVERSION_TYPE	VARCHAR2(20 BYTE),
CONVERSION_RATE	NUMBER,
INVERSE_CONVERSTION_RATE	NUMBER
);
/

create or replace TYPE WSC_AHCS_LSI_EXCHANGE_RATE_T_TYPE_TABLE 
AS TABLE OF  WSC_AHCS_LSI_EXCHANGE_RATE_T_TYPE;
/

create or replace TYPE          "WSC_AHCS_LSI_LOOKUP_T_TYPE" FORCE AS OBJECT 
( 
LOOKUP_TYPE	VARCHAR2(100 BYTE),
LOOKUP_CODE	VARCHAR2(100 BYTE),
MEANING	VARCHAR2(100 BYTE),
DESCRIPTION	VARCHAR2(200 BYTE),
ATTRIBUTE1	VARCHAR2(100 BYTE),
ATTRIBUTE2	VARCHAR2(100 BYTE),
TAG      	VARCHAR2(100 BYTE),
LEDGER_NAME	VARCHAR2(100 BYTE),
CURRENCY_CODE VARCHAR2(100 BYTE),
ATTRIBUTE3	VARCHAR2(100 BYTE),
ATTRIBUTE4	VARCHAR2(100 BYTE)
);
/

create or replace TYPE WSC_AHCS_LSI_LOOKUP_T_TYPE_TABLE 
AS TABLE OF  WSC_AHCS_LSI_LOOKUP_T_TYPE;
/

create or replace TYPE        WSC_LSI_APAR_T_TYPE force AS OBJECT 
( Record_Type VARCHAR2(5 BYTE), 
   FILE_NAME  VARCHAR2(200 BYTE),
	BU VARCHAR2(200 BYTE),
    BU_ID VARCHAR2(200 BYTE),
	INVOICE_NUMBER VARCHAR2(100 BYTE), 
    INVOICE_ID VARCHAR2(100 BYTE),
	LEDGER_NAME VARCHAR2(100 BYTE), 
	ACCOUNTING_CLASS VARCHAR2(100 BYTE), 
	INVOICE_DATE DATE, 
	ACCOUNTING_DATE DATE, 
	EXCHANGE_RATE NUMBER, 
	EXCHANGE_RATE_TYPE VARCHAR2(100 BYTE), 
	EXCHANGE_RATE_DATE DATE, 
	ENTERED_INVOICE_AMOUNT NUMBER, 
	ACCOUNTED_INVOICE_AMOUNT NUMBER, 
	GL_CODE_COMBINATION VARCHAR2(200 BYTE), 
	INTERCOMPANY_LEGAL_ENTITY VARCHAR2(200 BYTE), 
	INTERCOMPANY_TRANSACTION_TYPE VARCHAR2(80 BYTE), 
	INTERCOMPANY_BATCH_NUMBER VARCHAR2(100 BYTE),
    BANK_ACC VARCHAR2(200 BYTE),
	VENDOR_CUST_NAME VARCHAR2(360 BYTE), 
	VENDOR_CUST_SITE VARCHAR2(240 BYTE), 
	Account_Number VARCHAR2(100 BYTE), 
	Lockbox_Number VARCHAR2(50 BYTE), 
    Lockbox_ID VARCHAR2(200 BYTE),
	Bank_Origination_Number VARCHAR2(50 BYTE), 
	Invoice_Currency_Code VARCHAR2(5 BYTE), 
	Functional_Currency_Code VARCHAR2(5 BYTE),
    Netting_Ledger VARCHAR2(100 BYTE), 
    Netting_Fun_Curr VARCHAR2(5 BYTE),
    IC_TRX_NUMBER VARCHAR2(100 BYTE),
    ACCOUNTING_PERIOD VARCHAR2(20 BYTE)
);
/

create or replace type WSC_LSI_APAR_T_TYPE_TABLE is table of WSC_LSI_APAR_T_TYPE;
/

create or replace TYPE          "WSC_LSI_CREDIT_MEMO_INVOICE_TYPE" force AS OBJECT  
(  invoice_id varchar2(30),
invoice_num varchar2(100),
vendor_name varchar2(360),
vendor_site_code varchar2(240),
operating_unit varchar2(30),
status varchar2(30),
legal_entity_name varchar2(250),
load_request_id varchar2(30)
);
/

create or replace TYPE          "WSC_LSI_CREDIT_MEMO_INVOICE_TYPE_TABLE" is table of wsc_lsi_credit_memo_invoice_type;
/

create or replace TYPE        WSC_LSI_RECEIPT_CREATED_T_TYPE force AS OBJECT  
(  RECEIPT_NUMBER  VARCHAR2(100 BYTE),
   CURRENCY_CODE VARCHAR2(5 BYTE),
   AMOUNT NUMBER,
   STATUS VARCHAR2(50 BYTE), 
    ORG_ID VARCHAR2(100 BYTE),
    REQUEST_ID NUMBER
);
/

create or replace type WSC_LSI_RECEIPT_CREATED_T_TYPE_TABLE is table of WSC_LSI_RECEIPT_CREATED_T_TYPE;
/