SET ECHO ON;
SET DEFINE OFF;

PROMPT "EXECUTING WSC_LSI_SEQUENCES.sql";
@WSC_LSI_SEQUENCES.sql

PROMPT "EXECUTING WSC_LSI_TABLES.sql";
@WSC_LSI_TABLES.sql

PROMPT "EXECUTING WSC_LSI_INDEXES.sql"
@WSC_LSI_INDEXES.sql

PROMPT "EXECUTING WSC_LSI_TABLE_TYPES.sql"
@WSC_LSI_TABLE_TYPES.sql

PROMPT "EXECUTING WSC_LSI_PKG.sql"
@WSC_LSI_PKG.sql

PROMPT "EXECUTING WSC_LSI_PKG_BODY.sql"
@WSC_LSI_PKG_BODY.sql

PROMPT "EXECUTING XLSX_BUILDER_PKG.sql"
@XLSX_BUILDER_PKG.sql

PROMPT "EXECUTING XLSX_BUILDER_PKG_BODY.sql"
@XLSX_BUILDER_PKG_BODY.sql

PROMPT "EXECUTING WSC_WSC_AHCS_REFRESH_T.sql" 
@WSC_WSC_AHCS_REFRESH_T.sql

COMMIT;