SET DEFINE OFF;

PROMPT "EXECUTING WSC_COMMON_AHCS_PURGING_PKG_BODY.sql";
@WSC_AHCS_INT_ERROR_LOGGING.sql;
@WSC_AHCS_INT_ERROR_LOGGING_BODY.sql;
PROMPT "EXECUTING WSC_COMMON_AHCS_PURGING_PKG_BODY.sql";
@WSC_AHCS_PURGING_PKG_BODY.sql
commit;