CREATE INDEX  "WSC_GL_USER_COA_MAPPING_BATCH_ID_I" ON  "WSC_GL_USER_COA_MAPPING_T" ("BATCH_ID");

CREATE INDEX  "WSC_GL_USER_COA_MAPPING_COA_MAP_NAME_I" ON  "WSC_GL_USER_COA_MAPPING_T" ("COA_MAP_NAME");

CREATE INDEX  "WSC_GL_USER_ADFDI_MAPPING_BATCH_ID_I" ON  "WSC_GL_ADFDI_COA_MAPPING_T" ("BATCH_ID");

CREATE INDEX  "WSC_GL_USER_ADFDI_MAPPING_COA_MAP_NAME_I" ON  "WSC_GL_ADFDI_COA_MAPPING_T" ("COA_MAP_NAME");
