CREATE OR REPLACE TRIGGER  "WSC_USER_COA_MAPPING_BIR" BEFORE INSERT ON WSC_GL_USER_COA_MAPPING_T
FOR EACH ROW
   WHEN (new."LINE_ID" IS NULL) BEGIN
  SELECT WSC_GL_USER_COA_MAPPING_T_S.nextVal 
  INTO :new."LINE_ID" 
  FROM dual;
END;
/
CREATE OR REPLACE TRIGGER  "WSC_GL_ADFDI_COA_MAPPING_BIR" BEFORE INSERT ON WSC_GL_ADFDI_COA_MAPPING_T
FOR EACH ROW
   WHEN (new."LINE_ID" IS NULL) BEGIN
  SELECT WSC_GL_USER_COA_MAPPING_T_S.nextVal 
  INTO :new."LINE_ID" 
  FROM dual;
END;
/