--------------------------------------------------------
--   Type WSC_FA_HEADER_T_TYPE_TABLE
--------------------------------------------------------
-- DROP TYPE "FININT"."WSC_FA_HEADER_T_TYPE_TABLE"; 
-- DROP TYPE "FININT"."WSC_FA_HEADER_T_TYPE";
-- /

--------------------------------------------------------
--   Type WSC_FA_HEADER_T_TYPE
--------------------------------------------------------
  CREATE OR REPLACE TYPE "FININT"."WSC_FA_HEADER_T_TYPE" AS OBJECT 
( 
    TRANSACTION_DATE VARCHAR2(100), 
	TRANSACTION_NUMBER VARCHAR2(100), 
	LEDGER_NAME VARCHAR2(100), 
	SOURCE_TRN_NBR VARCHAR2(100), 
	SOURCE_SYSTEM VARCHAR2(100), 
	LEG_AE_HEADER_ID NUMBER, 
	EVENT_TYPE VARCHAR2(100), 
	EVENT_CLASS VARCHAR2(100), 
	ACC_DATE VARCHAR2(100), 
	ASSET_BOOK VARCHAR2(100), 
	ASSET_CAT VARCHAR2(100 ), 
	ASSET_DESC VARCHAR2(100), 
	HEADER_DESC VARCHAR(100),
	LED_LEG_NAME VARCHAR2(100), 
	JE_NAME VARCHAR2(100), 
	JE_CATEGORY VARCHAR2(100), 
	TRN_AMOUNT NUMBER,
	FILE_NAME VARCHAR2(100), 
	TRANSACTION_TYPE VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	CREATION_DATE VARCHAR2(100), 
	LAST_UPDATED_BY VARCHAR2(100), 
	LAST_UPDATE_DATE VARCHAR2(100), 
	ATTRIBUTE1 VARCHAR2(100), 
	ATTRIBUTE2 VARCHAR2(100), 
	ATTRIBUTE3 VARCHAR2(100), 
	ATTRIBUTE4 VARCHAR2(100), 
	ATTRIBUTE5 VARCHAR2(100), 
	ATTRIBUTE6 NUMBER, 
	ATTRIBUTE7 NUMBER, 
	ATTRIBUTE8 NUMBER, 
	ATTRIBUTE9 VARCHAR2(100), 
	ATTRIBUTE10 VARCHAR2(100), 
	JE_BATCH_NAME VARCHAR2(100), 
	HEADER_ID NUMBER, 
	BATCH_ID NUMBER 
);
/
CREATE OR REPLACE TYPE "FININT"."WSC_FA_HEADER_T_TYPE_TABLE" 
AS TABLE OF WSC_FA_HEADER_T_TYPE;
/



--------------------------------------------------------
--   Type WSC_FA_LINE_T_TYPE
--------------------------------------------------------
-- DROP TYPE "FININT"."WSC_FA_LINE_T_TYPE_TABLE";
-- DROP TYPE "FININT"."WSC_FA_LINE_T_TYPE";
-- /

CREATE OR REPLACE TYPE "FININT"."WSC_FA_LINE_T_TYPE" AS OBJECT 
( 
	TRANSACTION_NUMBER VARCHAR2(100), 
	DEFAULT_AMOUNT NUMBER, 
	DEFAULT_CURRENCY VARCHAR2(100), 
	LEG_COA VARCHAR2(100), 
	LEG_SEG1 VARCHAR2(100), 
	LEG_SEG2 VARCHAR2(100), 
	LEG_SEG3 VARCHAR2(100), 
	LEG_SEG4 VARCHAR2(100), 
	LEG_SEG5 VARCHAR2(100), 
	LEG_SEG6 VARCHAR2(100), 
	LEG_SEG7 VARCHAR2(100), 
	GL_LEGAL_ENTITY VARCHAR2(100), 
	GL_ACCT VARCHAR2(100), 
	GL_OPER_GRP VARCHAR2(100), 
	GL_DEPT VARCHAR2(100), 
	GL_SITE VARCHAR2(100), 
	GL_IC VARCHAR2(100), 
	GL_PROJECTS VARCHAR2(100), 
	GL_FUT_1 VARCHAR2(100), 
	GL_FUT_2 VARCHAR2(100), 
	ACC_CLASS VARCHAR2(100), 
	ACC_AMT NUMBER, 
	DR_CR_FLAG VARCHAR2(100), 
	JE_LINE_NBR NUMBER, 
	LINE_DESC VARCHAR2(2000), 
	TRANSACTION_TYPE VARCHAR2(100), 
	ACC_CURRENCY VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	CREATION_DATE VARCHAR2(100), 
	LAST_UPDATED_BY VARCHAR2(100), 
	LAST_UPDATE_DATE VARCHAR2(100), 
	LINE_ID NUMBER, 
	BATCH_ID NUMBER, 
	ATTRIBUTE1 VARCHAR2(100), 
	ATTRIBUTE2 VARCHAR2(100), 
	ATTRIBUTE3 VARCHAR2(100), 
	ATTRIBUTE4 VARCHAR2(100), 
	ATTRIBUTE5 VARCHAR2(100), 
	ATTRIBUTE6 NUMBER, 
	ATTRIBUTE7 NUMBER, 
	ATTRIBUTE8 NUMBER, 
	ATTRIBUTE9 NUMBER, 
	ATTRIBUTE10 NUMBER, 
	ATTRIBUTE11 VARCHAR2(100), 
	ATTRIBUTE12 VARCHAR2(100), 
	TARGET_COA VARCHAR2(200),
    LEG_AE_HEADER_ID NUMBER,
	LEG_AE_LINE_NBR NUMBER,
    SOURCE_TRN_NBR VARCHAR2(100)
    ); 
/	
CREATE OR REPLACE TYPE "FININT"."WSC_FA_LINE_T_TYPE_TABLE" 
AS TABLE OF WSC_FA_LINE_T_TYPE;
/
