SET ECHO ON;

PROMPT "EXECUTING WSC_AXE_INT020_TABLE.sql";
@WSC_AXE_INT020_TABLE.sql;

PROMPT "EXECUTING WSC_AXE_INT020_INDEXES.sql";
@WSC_AXE_INT020_INDEXES.sql

PROMPT "EXECUTING WSC_AXE_INT020_SEQUENCES.sql";
@WSC_AXE_INT020_SEQUENCES.sql

PROMPT "EXECUTING WSC_AXE_INT020_TABLE_TYPES.sql";
@WSC_AXE_INT020_TABLE_TYPES.sql;

PROMPT "EXECUTING WSC_AXE_INT020_PKG.sql";
@WSC_AXE_INT020_PKG.sql

PROMPT "EXECUTING WSC_AXE_INT020_PKG_BODY.sql";
@WSC_AXE_INT020_PKG_BODY.sql

PROMPT "EXECUTING WSC_AXE_INT020_VALIDATION_TRANSFORMATION_PKG.sql";
@WSC_AXE_INT020_VALIDATION_TRANSFORMATION_PKG.sql

PROMPT "EXECUTING WSC_AXE_INT020_VALIDATION_TRANSFORMATION_PKG_BODY.sql";
@WSC_AXE_INT020_VALIDATION_TRANSFORMATION_PKG_BODY.sql

COMMIT;
