

--------------------------------------------------------
--  DDL for Table WSC_AHCS_CENTRAL_TXN_STG_T
--------------------------------------------------------
  PROMPT "CREATING TABLE WSC_AHCS_CENTRAL_TXN_STG_T";
  
  CREATE TABLE "FININT"."WSC_AHCS_CENTRAL_TXN_STG_T" 
   (	"BATCH_ID" NUMBER, 
	"RICE_ID" VARCHAR2(10 BYTE), 
	"DATA_STRING" VARCHAR2(200 BYTE)
   );



--------------------------------------------------------
--  DDL for Table WSC_AHCS_CENTRAL_TXN_HEADER_T
--------------------------------------------------------
  PROMPT "CREATING TABLE WSC_AHCS_CENTRAL_TXN_HEADER_T";
  
  CREATE TABLE "FININT"."WSC_AHCS_CENTRAL_TXN_HEADER_T" 
   (	"HEADER_ID" NUMBER, 
	"BATCH_ID" NUMBER, 
	"TRANSACTION_DATE" DATE, 
	"TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"LEDGER_NAME" VARCHAR2(50 BYTE), 
	"JE_CODE" VARCHAR2(30 BYTE), 
	"JE_CATEGORY" VARCHAR2(100 BYTE), 
	"FILE_NAME" VARCHAR2(100 BYTE), 
	"FILE_EXT_DATE" DATE, 
	"SOURCE_SYSTEM" VARCHAR2(20 BYTE), 
	"FILE_RECORDS_COUNT" NUMBER, 
	"EVENT_TYPE" VARCHAR2(20 BYTE), 
	"ACCOUNTING_DATE" DATE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" NUMBER, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" DATE, 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE),
	"DIFF_AMOUNT" NUMBER
   );
   

   
--------------------------------------------------------
--  DDL for Table WSC_AHCS_CENTRAL_TXN_LINE_T
--------------------------------------------------------
  PROMPT "CREATING TABLE WSC_AHCS_CENTRAL_TXN_LINE_T";
  
  CREATE TABLE "FININT"."WSC_AHCS_CENTRAL_TXN_LINE_T" 
   (	"LINE_ID" NUMBER, 
	"HEADER_ID" NUMBER, 
	"BATCH_ID" NUMBER, 
	"TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"JE_LINE_NBR" NUMBER, 
	"DEFAULT_AMOUNT" NUMBER, 
	"DEFAULT_CURRENCY" VARCHAR2(20 BYTE), 
	"ACC_AMT" NUMBER, 
	"ACC_CURRENCY" VARCHAR2(20 BYTE), 
	"WIC" VARCHAR2(50 BYTE), 
	"JE_CODE" VARCHAR2(20 BYTE), 
	"LEDGER_NAME" VARCHAR2(100 BYTE), 
	"LEG_SEG2" VARCHAR2(10 BYTE), 
	"LEG_SEG3" VARCHAR2(10 BYTE), 
	"LEG_COA" VARCHAR2(20 BYTE), 
	"GL_LEGAL_ENTITY" VARCHAR2(10 BYTE), 
	"GL_OPER_GRP" VARCHAR2(10 BYTE), 
	"GL_ACCT" VARCHAR2(10 BYTE), 
	"GL_DEPT" VARCHAR2(10 BYTE), 
	"GL_SITE" VARCHAR2(10 BYTE), 
	"GL_IC" VARCHAR2(10 BYTE), 
	"GL_PROJECTS" VARCHAR2(10 BYTE), 
	"GL_FUT_1" VARCHAR2(10 BYTE), 
	"GL_FUT_2" VARCHAR2(10 BYTE), 
	"DR_CR_FLAG" VARCHAR2(2 BYTE), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" NUMBER, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" DATE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"TARGET_COA" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE)
   );



--------------------------------------------------------
--  DDL for Table WSC_AHCS_CENTRAL_JE_CTG_MAP_T
--------------------------------------------------------
  PROMPT "CREATING TABLE WSC_AHCS_CENTRAL_JE_CTG_MAP_T";

  CREATE TABLE "FININT"."WSC_AHCS_CENTRAL_JE_CTG_MAP_T" 
   (	"JE_CODE" VARCHAR2(30 BYTE), 
	"JE_CATEGORY" VARCHAR2(100 BYTE), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" NUMBER, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" DATE, 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE)
   );

COMMIT;