SET ECHO ON;
SET DEFINE OFF;

@CREATE_WSC_AHCS_CENTRAL_TXN_LINE_T_BKP_5_2_2023.sql;
@CREATE_WSC_AHCS_INT_STATUS_T_5_2_2023.sql;
@UPDATE_WSC_AHCS_INT_STATUS_T.sql;
@UPDATE_WSC_AHCS_CENTRAL_TXN_LINE_T.sql;

COMMIT;



