SET DEFINE OFF;
@WSC_INT184_TXN_HEADER_LINE_T.sql
@WSC_INT184_INDEXES.sql
@WSC_INT184_SEQUENCE.sql
@WSC_INT184_TABLE_TYPE.sql
@WSC_INT184_PKG.sql
@WSC_INT184_PKG_body.sql
@WSC_INT184_VALIDATION_TRANSFORMATION_PKG.sql
@WSC_INT184_VALIDATION_TRANSFORMATION_PKG_body.sql
commit;