CREATE INDEX "FININT"."WSC_AHCS_CNCR_TXN_HEADER_BATCH_ID_N1" ON "FININT"."WSC_AHCS_CNCR_TXN_HEADER_T" ("BATCH_ID");
CREATE INDEX "FININT"."WSC_AHCS_CNCR_TXN_LINE_BATCH_ID_N1" ON "FININT"."WSC_AHCS_CNCR_TXN_LINE_T" ("BATCH_ID");
CREATE INDEX "FININT"."WSC_AHCS_CNCR_TXN_LINE_HEADER_ID_N1" ON "FININT"."WSC_AHCS_CNCR_TXN_LINE_T" ("HEADER_ID");
CREATE INDEX "FININT"."WSC_AHCS_CNCR_TXN_LINE_LEG_COA_N1" ON "FININT"."WSC_AHCS_CNCR_TXN_LINE_T" ("LEG_COA");
CREATE INDEX "FININT"."WSC_AHCS_CNCR_TMP_T_REG_N1" ON "FININT"."WSC_AHCS_CNCR_TXN_TMP_T" (regexp_substr(data_string, '([^|]*)(\||$)', 1, 1, NULL,1));
CREATE INDEX "FININT"."WSC_AHCS_CNCR_TXN_TMP_BATCH_ID_N1" ON "FININT"."WSC_AHCS_CNCR_TXN_TMP_T" ("BATCH_ID");

ALTER INDEX WSC_AHCS_CNCR_TXN_HEADER_BATCH_ID_N1 REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_CNCR_TXN_HEADER_T_PK REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_CNCR_TXN_LINE_BATCH_ID_N1 REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_CNCR_TXN_LINE_HEADER_ID_N1 REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_CNCR_TXN_LINE_LEG_COA_N1 REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_CNCR_TXN_LINE_T_PK REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_CNCR_TMP_T_REG_N1 REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_CNCR_TXN_TMP_BATCH_ID_N1 REBUILD COMPUTE STATISTICS;