
	drop MATERIALIZED VIEW  WSC_AHCS_DASHBOARD1_V;
  CREATE MATERIALIZED VIEW "FININT"."WSC_AHCS_DASHBOARD1_V" ("APPLICATION", "SOURCE_SYSTEM", "FILE_NAME", "FILE_PROCESSING_DATE", "BATCH_ID", "STAGED_RECORDS", "STAGED_AMOUNT", "PROCESSED_RECORDS", "PROCESSED_AMOUNT", "ERROR_REEXTRACT_RECORDS", "ERROR_REEXTRACT_AMOUNT", "ERROR_REPROCESS_RECORDS", "ERROR_REPROCESS_AMOUNT", "SKIPPED_RECORDS", "SKIPPED_AMOUNT", "IMPORT_ACCOUNTING_ERROR")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS Select 
  decode(application,'ERP_POC','ERP POC','CENTRAL','Central','ECLIPSE','ECLPS','SXE','SXEUS','TW','APS Treasury','MF INV','MF INVENTORY',application) Application,
--       case when application = 'MF INV' then substr(WAIS.ATTRIBUTE3,1,3)
--       else
--       decode(WAIC.ATTRIBUTE3,'SALE','SII','CASH','CRI','LSIR','LSI','SPER','SPR','ARIN','ARI',substr(WAIC.ATTRIBUTE3,1,3)) end 
--    decode(decode(WAIC.ATTRIBUTE3,'SALE','SII','CASH','CRI','LSIR','LSI','SPER','SPR','ARIN','ARI',substr(WAIC.ATTRIBUTE3,1,3)),'IFR','FII','COQ','CQI','OFR','FTI','INT','ICI','INV','ISI','SPE','SPC',substr(WAIC.ATTRIBUTE3,1,3)) SOURCE_SYSTEM,
    case when application = 'MF AR' then
        decode(WAIC.ATTRIBUTE3,'SALE','SII','CASH','CRI','LSIR','LSI','SPER','SPR','ARIN','ARI',substr(WAIC.ATTRIBUTE3,1,3))
    when application = 'MF INV' then
     decode(substr(WAIC.ATTRIBUTE3,1,3),'IFR','FII','COQ','CQI','OFR','FTI','INT','ICI','INV','ISI','SPE','SPC',
        substr(WAIC.ATTRIBUTE3,1,3))
    else
    substr(WAIC.ATTRIBUTE3,1,3) end  SOURCE_SYSTEM,        

       WAIS.File_name,
       to_char(WAIC.CREATED_DATE at time zone 'EST','YYYY-MM-DD HH24:MI:SS') FILE_PROCESSING_DATE,
       WAIS.Batch_ID,
       count(*) STAGED_RECORDS,
       WSC_AHCS_DASHBOARD.get_STAGED_AMOUNT(WAIS.batch_id,WAIS.File_name,WAIS.Application) STAGED_AMOUNT,
       WSC_AHCS_DASHBOARD.get_PROCESSED_RECORDS(WAIS.batch_id,WAIS.File_name,WAIS.Application) PROCESSED_RECORDS,
       WSC_AHCS_DASHBOARD.get_PROCESSED_AMOUNT(WAIS.batch_id,WAIS.File_name,WAIS.Application) PROCESSED_AMOUNT,
       WSC_AHCS_DASHBOARD.get_ERROR_REEXTRACT_RECORDS(WAIS.batch_id,WAIS.File_name,WAIS.Application) ERROR_REEXTRACT_RECORDS,
       WSC_AHCS_DASHBOARD.get_ERROR_REEXTRACT_AMOUNT(WAIS.batch_id,WAIS.File_name,WAIS.Application) ERROR_REEXTRACT_AMOUNT,
       WSC_AHCS_DASHBOARD.get_ERROR_REPROCESS_RECORDS(WAIS.batch_id,WAIS.File_name,WAIS.Application) ERROR_REPROCESS_RECORDS,
       WSC_AHCS_DASHBOARD.get_ERROR_REPROCESS_AMOUNT(WAIS.batch_id,WAIS.File_name,WAIS.Application) ERROR_REPROCESS_AMOUNT,
       WSC_AHCS_DASHBOARD.get_SKIPPED_RECORDS(WAIS.batch_id,WAIS.File_name,WAIS.Application) SKIPPED_RECORDS,
       WSC_AHCS_DASHBOARD.get_SKIPPED_AMOUNT(WAIS.batch_id,WAIS.File_name,WAIS.Application) SKIPPED_AMOUNT,
       WSC_AHCS_DASHBOARD.GET_IMPORT_ACCOUNT_ERROR(WAIS.batch_id,WAIS.File_name,WAIS.Application) IMPORT_ACCOUNTING_ERROR
FROM  WSC_AHCS_INT_STATUS_T WAIS,
                WSC_AHCS_INT_CONTROL_T WAIC      
WHere WAIS.BATCH_ID=WAIC.BATCH_ID
AND        WAIS.Application=decode(WAIC.SOURCE_APPLICATION,'SALES_COM','CENTRAL','CENTRAL_INV','CENTRAL',WAIC.SOURCE_APPLICATION)
AND   WAIS.File_name=WAIC.File_name                            
GROUP BY Application,
       WAIS.File_name,
       WAIS.Batch_ID,
       WAIC.CREATED_DATE,
       WAIC.ATTRIBUTE3;

   COMMENT ON MATERIALIZED VIEW "FININT"."WSC_AHCS_DASHBOARD1_V"  IS 'snapshot table for snapshot FININT.WSC_AHCS_DASHBOARD1_V';

