--DROP statements

SET ECHO ON;
DROP TABLE "FININT"."WSC_AHCS_AR_TXN_HEADER_T" ;
DROP TABLE "FININT"."WSC_AHCS_AR_TXN_LINE_T" ;
DROP SEQUENCE "FININT"."WSC_AR_HEADER_S1";
DROP SEQUENCE "FININT"."WSC_AR_LINE_S1";
DROP TYPE "FININT"."WSC_AR_HEADER_T_TYPE"  force;
DROP TYPE "FININT"."WSC_AR_LINE_T_TYPE"  force;
DROP TYPE "FININT"."WSC_AR_HEADER_T_TYPE_TABLE"  force;
DROP TYPE "FININT"."WSC_AR_LINE_T_TYPE_TABLE"  force;
commit;
