--DROP statements

SET ECHO ON;
DROP TABLE "FININT"."WSC_AHCS_AP_TXN_HEADER_T" ;
DROP TABLE "FININT"."WSC_AHCS_AP_TXN_LINE_T" ;
DROP SEQUENCE "FININT"."WSC_AP_HEADER_T_S1";
DROP SEQUENCE "FININT"."WSC_AP_LINE_T_S1";
DROP TYPE "FININT"."WSC_AP_HEADER_T_TYPE"  force;
DROP TYPE "FININT"."WSC_AP_LINE_T_TYPE"  force;
DROP TYPE "FININT"."WSC_AP_HEADER_T_TYPE_TABLE"  force;
DROP TYPE "FININT"."WSC_AP_LINE_T_TYPE_TABLE"  force;
commit;
