--DROP statements

DROP TABLE "FININT"."WSC_GL_USER_COA_MAPPING_H" ;
DROP TABLE "FININT"."WSC_GL_USER_COA_MAPPING_T" ;
DROP TABLE "FININT"."WSC_GL_ADFDI_COA_MAPPING_T";
DROP TABLE "FININT"."WSC_GL_ADFDI_EXCEL_TEMPLATE_T";
DROP SEQUENCE "FININT"."WSC_GL_USER_COA_MAPPING_H_S";
DROP SEQUENCE "FININT"."WSC_GL_USER_COA_MAPPING_T_S";
DROP SEQUENCE "FININT"."WSC_GL_USER_JOB_NAME_S";