--DROP statements

DROP TABLE "FININT"."WSC_GL_CONSOLIDATION_RULE_ERR_T" ;
DROP TABLE "FININT"."WSC_GL_CCID_MAPPING_ERR_T" ;
DROP SEQUENCE "FININT"."WSC_GL_CCID_DISABLE_SEQ";
DROP SEQUENCE "FININT"."WSC_GL_COA_DISABLE_VER_SEQ";
DROP SEQUENCE "FININT"."WSC_GL_COA_DISABLE_SEQ";