--DROP statements

DROP TABLE "FININT"."WSC_GL_LEGAL_ENTITIES_T";
DROP TABLE "FININT"."WSC_AHCS_DASHBOARD1_AUDIT_T";
DROP TABLE "FININT"."WSC_AHCS_INT_CONTROL_T";
DROP TABLE "WSC_AHCS_INT_STATUS_T";
DROP TABLE "WSC_AHCS_INT_LOGGING_T";
DROP TABLE "WSC_AHCS_REFRESH_T";
DROP TABLE "XX_IMD_DETAILS";
DROP TABLE "XX_IMD_USER_ROLE_DETAILS_T";
DROP SEQUENCE  "FININT"."WSC_AHCS_BATCH_SEQ";
DROP TYPE "FININT"."WSC_GL_LEGAL_ENTITIES_VALUE_T_TYPE"  force;
DROP TYPE "FININT"."WSC_GL_LEGAL_ENTITIES_VALUE_T_TYPE_TABLE"  force;