DROP TABLE "FININT"."WSC_AHCS_FA_TXN_HEADER_T" ;
DROP TABLE "FININT"."WSC_AHCS_FA_TXN_LINE_T";
DROP SEQUENCE  "FININT"."WSC_FA_HEADER_ID_S1" ;
DROP SEQUENCE  "FININT"."WSC_FA_LINE_ID_S1" ;
DROP TYPE "FININT"."WSC_FA_HEADER_T_TYPE" force;
DROP TYPE "FININT"."WSC_FA_LINE_T_TYPE" force;
DROP TYPE "FININT"."WSC_FA_HEADER_T_TYPE_TABLE" force;
DROP TYPE "FININT"."WSC_FA_LINE_T_TYPE_TABLE" force;