DROP TABLE "FININT"."WSC_AHCS_POC_TXN_HEADER_T" ;
DROP TABLE "FININT"."WSC_AHCS_POC_TXN_LINE_T";
DROP SEQUENCE  "FININT"."WSC_POC_HEADER_S1" ;
DROP SEQUENCE  "FININT"."WSC_POC_LINE_S1" ;
DROP TYPE "FININT"."WSC_POC_HEADER_RT" force;
DROP TYPE "FININT"."WSC_POC_LINE_RT" force;
DROP TYPE "FININT"."WSC_POC_HEADER_TT" force;
DROP TYPE "FININT"."WSC_POC_LINE_TT" force;