DROP SEQUENCE "FININT"."WSC_AHCS_RECON_RECORDS_SEQ";
DROP TABLE "FININT"."WSC_AHCS_RECON_REP_TEMP_T";
DROP TYPE "FININT"."WSC_AHCS_RECON_REP_TEMP_T_TYPE" FORCE;
DROP TYPE "FININT"."WSC_AHCS_RECON_REP_TEMP_T_TAB" FORCE;

