--DROP statements

DROP TABLE "FININT"."WSC_GL_COA_MAP_T" ;
DROP TABLE "FININT"."WSC_GL_COA_SYSTEM_DEFINITIONS_T" ;
DROP TABLE "FININT"."WSC_GL_COA_SEGMENT_DEFINITIONS_T";
DROP TABLE "FININT"."WSC_GL_COA_MAPPING_RULES_T";
DROP TABLE "FININT"."WSC_GL_COA_SEGMENT_VALUE_T";
DROP TABLE "FININT"."WSC_GL_CCID_MAPPING_T";
DROP TABLE "FININT"."WSC_AHCS_COA_CONCAT_SEGMENT";
DROP TABLE "FININT"."WSC_TBL_TIME_T";
DROP SEQUENCE "FININT"."WSC_GL_CCID_MAPPING_S";
DROP SEQUENCE "FININT"."WSC_GL_COA_SAGMENT_VALUE_SEQ";
DROP SEQUENCE "FININT"."WSC_SEQ";