Create OR REPLACE TYPE WSC_AHCS_RECON_REP_TEMP_T_TYPE AS OBJECT
    (FILE_NAME VARCHAR2(150),
     TRX_NUMBER VARCHAR2(30),
     JOB_ID VARCHAR2(10),
     STATUS VARCHAR2(20),
     COMPLETION_DATE DATE);
/

create OR REPLACE TYPE WSC_AHCS_RECON_REP_TEMP_T_TAB AS TABLE OF WSC_AHCS_RECON_REP_TEMP_T_TYPE;
/

