SET ECHO ON;
SET DEFINE OFF;

PROMPT "EXECUTING WSC_EXTENSION_238_SEQUENCE.sql";
@WSC_EXTENSION_238_SEQUENCE.sql

PROMPT "EXECUTING WSC_EXTENSION_238_TABLE.sql";
@WSC_EXTENSION_238_TABLE.sql;

PROMPT "EXECUTING WSC_EXTENSION_238_TABLE_TYPE.sql";
@WSC_EXTENSION_238_TABLE_TYPE.sql;

PROMPT "EXECUTING WSC_EXTENSION_238_INDEX.sql";
@WSC_EXTENSION_238_INDEX.sql

PROMPT "EXECUTING WSC_EXTENSION_238_TRIGGER.sql";
@WSC_EXTENSION_238_TRIGGER.sql

PROMPT "EXECUTING WSC_TEMPLATE_DATA_INSERTION.sql";
@WSC_TEMPLATE_DATA_INSERTION.sql

PROMPT "EXECUTING WSC_INTER_INTRA_COMPANY_VALIDATION_PKG.sql";
@WSC_INTER_INTRA_COMPANY_VALIDATION_PKG.sql

PROMPT "EXECUTING WSC_INTER_INTRA_COMPANY_VALIDATION_PKG_BODY.sql";
@WSC_INTER_INTRA_COMPANY_VALIDATION_PKG_BODY.sql

PROMPT "EXECUTING WSC_USER_DATA_ACCESS_PKG.sql";
@WSC_USER_DATA_ACCESS_PKG.sql

PROMPT "EXECUTING WSC_USER_DATA_ACCESS_PKG_BODY.sql";
@WSC_USER_DATA_ACCESS_PKG_BODY.sql

COMMIT;