

 CREATE INDEX "FININT"."WSC_AHCS_ECLPS_TXN_HDR_BATCH_I" ON "FININT"."WSC_AHCS_ECLIPSE_TXN_HEADER_T" ("BATCH_ID");
 CREATE INDEX "FININT"."WSC_AHCS_ECLPS_TXN_LN_HDR_ID_I" ON "FININT"."WSC_AHCS_ECLIPSE_TXN_LINE_T" ("HEADER_ID");
 CREATE INDEX "FININT"."WSC_AHCS_ECLPS_TXN_LNE_BATCH_I" ON "FININT"."WSC_AHCS_ECLIPSE_TXN_LINE_T" ("BATCH_ID");
 
 
ALTER INDEX WSC_AHCS_ECLPS_TXN_HDR_BATCH_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_ECLPS_TXN_LN_HDR_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_ECLPS_TXN_LNE_BATCH_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_ECLPS_TXN_LINE_T_PK REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_ECLPS_TXN_HDR_T_PK REBUILD COMPUTE STATISTICS;