create or replace Package WSC_AHCS_RECON_RECORDS_PKG IS 

PROCEDURE INSERT_REC(P_INS_VAL WSC_AHCS_RECON_REP_TEMP_T_TAB,
                     ERRBUF OUT VARCHAR2,
                     RETCODE OUT VARCHAR2);
PROCEDURE CALL_ASYC_UPDATE(ERRBUF OUT VARCHAR2,
                     RETCODE OUT VARCHAR2);     

PROCEDURE UPDATE_REC(ERRBUF OUT VARCHAR2,
                     RETCODE OUT VARCHAR2);

PROCEDURE REFRESH_VALIDATION_OIC(RECTCODE OUT NUMBER,
                                ERRBUF OUT VARCHAR2) ;                     

END WSC_AHCS_RECON_RECORDS_PKG;
/
