SET DEFINE OFF;
@WSC_INT004_TABLE.sql
@WSC_INT004_INDEXES.sql
@WSC_INT004_SEQUENCE.sql
@WSC_INT004_TABLE_TYPE.sql
@WSC_INT004_PKG.sql
@WSC_INT004_PKG_BODY.sql
@WSC_INT004_VALIDATION_TRANSFORMATION_PKG.sql
@WSC_INT004_VALIDATION_TRANSFORMATION_PKG_BODY.sql
commit;