SET DEFINE OFF;
@WSC_COMMON_GL_TABLE.sql
@WSC_COMMON_GL_INDEX.sql
@WSC_COMMON_SEQUENCE.sql
@WSC_COMMON_GL_TABLE_TYPE.sql
@WSC_LOGGING_INSERT_PROCEDURE.sql
@WSC_COMMON_AHCS_REPROCESSING_PKG_SPEC.sql
@WSC_COMMON_AHCS_REPROCESSING_PKG_BODY.sql
@WSC_AHCS_INT_ERROR_LOGGING_SPEC.sql
@WSC_AHCS_INT_ERROR_LOGGING_BODY.sql
@WSC_COMMON_GL_LEGAL_ENTITIES_P.sql
@WSC_AHCS_BATCH_P_PROCEDURE.sql
--@WESCO_GATHER_STAT_JOB.sql
commit;