SET ECHO ON;
SET DEFINE OFF;

PROMPT "EXECUTING Update_WSC_GL_COA_MAPPING_RULES_T.sql";
@Update_WSC_GL_COA_MAPPING_RULES_T.sql;

PROMPT "EXECUTING Insert_WSC_GL_COA_MAPPING_RULES_T.sql";
@Insert_WSC_GL_COA_MAPPING_RULES_T.sql;

PROMPT "EXECUTING Trigger_WSC_COA_SEGMENT_VALUE_AIR.sql";
@Trigger_WSC_COA_SEGMENT_VALUE_AIR.sql;

COMMIT;



