 CREATE TABLE "FININT"."WSC_AHCS_INT_CONTROL_LINE_T" 
   (	"BATCH_ID" VARCHAR2(10 CHAR), 
	"FILE_NAME" VARCHAR2(100 CHAR), 
	"GROUP_ID" VARCHAR2(10 CHAR), 
	"LEDGER_NAME" VARCHAR2(20 CHAR), 
	"UCM_ID" VARCHAR2(200 CHAR), 
	"IMPORT_ACC_ID" VARCHAR2(200 CHAR), 
	"CREATE_ACC_ID" VARCHAR2(520 CHAR), 
	"SOURCE_SYSTEM" VARCHAR2(10 CHAR), 
	"INTERFACE_ID" VARCHAR2(10 CHAR), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"STATUS" VARCHAR2(50 BYTE), 
	"LEDGER_GRP_NUM" VARCHAR2(20 BYTE)
   );
   
  CREATE TABLE "FININT"."WSC_AHCS_INT_MF_LEDGER_T" 
   (	"SUB_LEDGER" VARCHAR2(10 CHAR), 
	"LEDGER_NAME" VARCHAR2(25 CHAR), 
	"LEDGER_GRP_NUM" NUMBER, 
	"STATIC_LEDGER_NUMBER" NUMBER
   ) ;
   
--------------------------------------------------------
--  File created - Friday-September-16-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WSC_AHCS_MF_BSR_ASSIGNMENT_LINE_T
--------------------------------------------------------

  CREATE TABLE "FININT"."WSC_AHCS_MF_BSR_ASSIGNMENT_LINE_T" 
   (	"GL_ACCOUNT" VARCHAR2(20 BYTE), 
	"BSR_ASSIGNMENT" VARCHAR2(20 BYTE)
   );
   
   
   ALTER TABLE "FININT"."WSC_AHCS_INT_CONTROL_T" 
ADD "GROUP_ID" VARCHAR2(10 CHAR);

  ALTER TABLE "FININT"."WSC_AHCS_INT_STATUS_T" 
ADD ("COMPANY_NUM" VARCHAR2(15 BYTE), 
	"PAY_CODE" VARCHAR2(30 BYTE), 
	"GL_CODE" VARCHAR2(30 BYTE), 
	"DR" NUMBER, 
	"CR" NUMBER, 
	"INTERFACE_ID" VARCHAR2(5 CHAR), 
	"LEDGER_NAME" VARCHAR2(50 BYTE), 
	"GROUP_ID" NUMBER);
	
	
	alter table
   wsc_ahcs_int_control_t
modify
(
   CREATE_ACC_ID    VARCHAR2(520 BYTE)
);

alter table
   wsc_ahcs_int_status_t
modify
(
   ERROR_MSG    VARCHAR2(540 BYTE)
);

alter table
   WSC_AHCS_DASHBOARD1_AUDIT_T
add
(
   SOURCE_SYSTEM VARCHAR2(12 BYTE)
);
  /*==================================================*/
           /*INDEX WSC_AHCS_INT_STATUS_T*/
  /*==================================================*/

CREATE INDEX "FININT"."WSC_AHCS_INT_STATUS_GRP_ID_I" ON "FININT"."WSC_AHCS_INT_STATUS_T" ("GROUP_ID") COMPUTE STATISTICS;
CREATE INDEX "FININT"."WSC_AHCS_INT_STATUS_LEDGER_NAME_I" ON "FININT"."WSC_AHCS_INT_STATUS_T" ("LEDGER_NAME") COMPUTE STATISTICS;

 /*==================================================*/
           /*COMMON LOOK UP TABLE FOR SKIP LE*/
  /*==================================================*/
  CREATE TABLE "FININT"."WSC_AHCS_INT_COM_LOOKUP_T" 
   (	"SOURCE" VARCHAR2(10 CHAR), 
	"ATTRIBUTE1" VARCHAR2(25 CHAR), 
	"ATTRIBUTE2" VARCHAR2(25 CHAR), 
	"ATTRIBUTE3" VARCHAR2(25 CHAR), 
	"ATTRIBUTE4" VARCHAR2(25 CHAR), 
	"ATTRIBUTE5" VARCHAR2(25 CHAR), 
	"ATTRIBUTE6" VARCHAR2(25 CHAR), 
	"ATTRIBUTE7" VARCHAR2(25 CHAR), 
	"ATTRIBUTE8" VARCHAR2(25 CHAR), 
	"ATTRIBUTE9" VARCHAR2(25 CHAR), 
	"ATTRIBUTE10" VARCHAR2(25 CHAR)
   );
