SET DEFINE OFF;
@WSC_INT124_TXN_HEADER_T_LINE_T_TMP_T.sql
@WSC_INT124_INDEXES.sql
@WSC_INT124_SEQUENCE.sql
@WSC_INT124_TMP_T_TYPE.sql
@WSC_INT124_PKG.sql
@WSC_INT124_PKG_BODY.sql
@wsc_INT124_validation_transformation_pkg.sql
@WSC_INT124_VALIDATION_TRANSFORMATION_PKG_BODY.sql
commit;