   ------------Objects Total#29-----------
  /*================================================*/
           /*TABLE TBL_TIME_T*/
  /*================================================*/
  CREATE TABLE "DGTL_PLS"."TBL_TIME_T" 
   ("A" VARCHAR2(2000 BYTE), 
	"B" DATE, 
	"C" NUMBER
   );
   

  /*================================================*/
           /*TABLE XX_COMMON_ERR_LOG_TBL*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_COMMON_ERR_LOG_TBL" 
   (	"SEQ_NO" VARCHAR2(100 BYTE), 
	"ERROR_IN_PROCEDURE" VARCHAR2(100 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"ERROR_LOG_DATE" VARCHAR2(100 BYTE)
   );
   
   

  /*================================================*/
           /*TABLE XX_CRIT_JOB_MAIN*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_CRIT_JOB_MAIN" 
   (	"DIFF_MINUTES" NUMBER, 
	"REQUESTID" NUMBER, 
	"DEFINITION" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE)
   ) ;
   
   
    /*================================================*/
           /*TABLE XX_IMD_ADDITIONAL_INFO_T*/
    /*================================================*/
  CREATE TABLE "DGTL_PLS"."XX_IMD_ADDITIONAL_INFO_T" 
   (	"ID" NUMBER, 
	"CREATIONDATE" VARCHAR2(2000 BYTE), 
	"LASTUPDATEDATE" VARCHAR2(2000 BYTE), 
	"CREATEDBY" VARCHAR2(2000 BYTE), 
	"LASTUPDATEDBY" VARCHAR2(2000 BYTE), 
	"KEYNAME" VARCHAR2(2000 BYTE), 
	"VALUE" VARCHAR2(2000 BYTE), 
	"INTEGRATION_ACTIVITY_ID" VARCHAR2(2000 BYTE), 
	 PRIMARY KEY ("ID")
   );
   
   
  /*================================================*/
           /*TABLE XX_IMD_ALERTS_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_ALERTS_T" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"SOURCE" VARCHAR2(30 BYTE), 
	"TRACK" VARCHAR2(30 BYTE), 
	"PRIORITY" VARCHAR2(30 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(100 BYTE), 
	"JOB_TYPE" VARCHAR2(30 BYTE), 
	"BODY" VARCHAR2(2000 BYTE), 
	"SUBJECT" VARCHAR2(100 BYTE), 
	"ATTACHMENT" BLOB, 
	"STATUS" VARCHAR2(30 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(500 BYTE), 
	"REQUESTER_ID" VARCHAR2(30 BYTE), 
	"PROGRAM_NAME" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50 BYTE), 
	"UPDATED_DATE" DATE
   ) ;



  /*================================================*/
           /*TABLE XX_IMD_DETAILS*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_DETAILS" 
   (	"USER_NAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"URL" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(100 BYTE), 
	"ATTRIBUTE2" VARCHAR2(100 BYTE), 
	"ATTRIBUTE3" VARCHAR2(100 BYTE), 
	"ATTRIBUTE4" VARCHAR2(100 BYTE), 
	"INSTANCE_NAME" VARCHAR2(200 BYTE)
   ) ;
   
   
  /*================================================*/
           /*INSERT XX_IMD_DETAILS*/
  /*================================================*/
   INSERT INTO XX_IMD_DETAILS (USER_NAME,PASSWORD,URL) VALUES ('FIN_INT','WescoAnixter@12345678901234567890','https://aictr-anixterpaas.integration.ocp.oraclecloud.com');
    
  /*================================================*/
           /*TABLE XX_IMD_INTEGRATION_RUN_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_INTEGRATION_RUN_T" 
   (	"ID" NUMBER, 
	"TOUCHPOINT_NAME" VARCHAR2(100 BYTE), 
	"TOUCHPOINT_STATUS" VARCHAR2(100 BYTE), 
	"INTEGRATION_STATUS" VARCHAR2(100 BYTE), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"INTEGRATION_MASTER_ID" NUMBER, 
	"TABLE_NAME" VARCHAR2(500 BYTE), 
	"LINK_NAME" VARCHAR2(500 BYTE), 
	"RUN_ID" VARCHAR2(100 BYTE), 
	"DM_NUMBER" VARCHAR2(100 BYTE), 
	"ORDER_ID" VARCHAR2(100 BYTE), 
	"GENCO_RID" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE), 
	"UPDATED_DATE" DATE, 
	"LOG_FILES" VARCHAR2(4000 BYTE), 
	"TRACK" VARCHAR2(100 BYTE), 
	"REQUEST_ID" NUMBER, 
	"RUN_IDENTIFIER" VARCHAR2(50 BYTE), 
	"RECON_ID" VARCHAR2(2000 BYTE), 
	"TICKET_NUMBER" VARCHAR2(100 BYTE), 
	"FILE_DATA" BLOB, 
	"MIME_TYPE" VARCHAR2(2000 BYTE), 
	 CONSTRAINT "XX_IMD_INTEG_RUN_T_PK" PRIMARY KEY ("ID")
   );

  

    /*================================================*/
           /*TABLE XX_IMD_INTEGRATION_ACTIVITY_T*/
     /*================================================*/
  CREATE TABLE "DGTL_PLS"."XX_IMD_INTEGRATION_ACTIVITY_T" 
   (	"ID" NUMBER, 
	"INTEGRATION_RUN_ID" NUMBER, 
	"ACTIVITY_NAME" VARCHAR2(2000 BYTE), 
	"ACTIVITY_DESC" VARCHAR2(2000 BYTE), 
	"ACTIVITY_DATE" TIMESTAMP (6), 
	"ACTIVITY_STATUS" VARCHAR2(100 BYTE), 
	"INT_RUN_ID" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE), 
	"UPDATED_DATE" DATE, 
	"TOUCHPOINT_NAME" VARCHAR2(100 BYTE), 
	 CONSTRAINT "XX_IMD_INTEG_ACTIVITY_T_PK" PRIMARY KEY ("ID")
   );

 
  /*================================================*/
           /*TABLE XX_IMD_INTEGRATION_INSTANCES_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_INTEGRATION_INSTANCES_T" 
   (	"ID" NUMBER, 
	"CREATIONDATE" VARCHAR2(2000 BYTE), 
	"LASTUPDATEDATE" VARCHAR2(2000 BYTE), 
	"CREATEDBY" VARCHAR2(2000 BYTE), 
	"LASTUPDATEDBY" VARCHAR2(2000 BYTE), 
	"INTEGRATION_STATUS" VARCHAR2(2000 BYTE), 
	"START_TIME" VARCHAR2(2000 BYTE), 
	"END_TIME" VARCHAR2(2000 BYTE), 
	"INTEGRATIONMASTERID" NUMBER, 
	"LINK_NAME" VARCHAR2(2000 BYTE), 
	 PRIMARY KEY ("ID")
   )  ;



  /*================================================*/
           /*TABLE XX_IMD_INTEGRATION_MASTER_T*/
  /*================================================*/
  CREATE TABLE "DGTL_PLS"."XX_IMD_INTEGRATION_MASTER_T" 
   (	"ID" NUMBER, 
	"INTEGRATION_CODE" VARCHAR2(100 BYTE), 
	"INTEGRATION_TYPE" VARCHAR2(100 BYTE), 
	"RICE_CODE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE), 
	"UPDATED_DATE" DATE, 
	"TRACK" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM" VARCHAR2(100 BYTE), 
	"TARGET_SYSTEM" VARCHAR2(50 BYTE), 
	"MODULE_CODE" VARCHAR2(20 BYTE), 
	"JOB_ID" NUMBER, 
	"INTEGRATION_NAME" CHAR(1000 BYTE), 
	 CONSTRAINT "XX_IMD_INTEG_MASTER_T_PK" PRIMARY KEY ("ID")
   );

  
  /*================================================*/
           /*TABLE XX_IMD_JOB_MASTER_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_JOB_MASTER_T" 
   (	"TRACK" VARCHAR2(30 BYTE), 
	"REQUESTER_ID" VARCHAR2(30 BYTE), 
	"REQUESTER_NAME" VARCHAR2(50 BYTE), 
	"JOB_NAME" VARCHAR2(2000 BYTE), 
	"JOB_TYPE" VARCHAR2(30 BYTE), 
	"CODE" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"ENABLE_FLAG" CHAR(1 BYTE), 
	"WEEKDAY_PRIORITY" NUMBER, 
	"WEEKEND_PRIORITY" NUMBER, 
	"MONTHEND_PRIORITY" NUMBER, 
	"THRESHOLD" VARCHAR2(30 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50 BYTE), 
	"UPDATED_DATE" DATE, 
	"WICER_ID" VARCHAR2(100 BYTE), 
	"ID" NUMBER
   ) ;


  /*================================================*/
           /*TABLE XX_IMD_JOB_RUN_T*/
  /*================================================*/
  CREATE TABLE "DGTL_PLS"."XX_IMD_JOB_RUN_T" 
   (	"TRACK" VARCHAR2(30 BYTE), 
	"REQUESTER_ID" VARCHAR2(30 BYTE), 
	"PROGRAM_NAME" VARCHAR2(100 BYTE), 
	"JOB_TYPE" VARCHAR2(30 BYTE), 
	"PHASE_CODE" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"ACTUAL_START_DATE" DATE, 
	"ACTUAL_END_DATE" DATE, 
	"RUN_TIME" NUMBER, 
	"STATUS" VARCHAR2(30 BYTE), 
	"LOG_FILES" BLOB, 
	"WICER_ID" VARCHAR2(30 BYTE), 
	"ARGUMENT_TEXT" VARCHAR2(500 BYTE), 
	"SUBMITTED_BY" VARCHAR2(50 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50 BYTE), 
	"UPDATED_DATE" DATE, 
	"LOG_FILE_PATH" VARCHAR2(1000 BYTE), 
	"REQUEST_ID" VARCHAR2(100 BYTE), 
	"REQ_SEQUENCE" NUMBER, 
	"TICKET_NUMBER" VARCHAR2(500 BYTE), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"SUBMIT_TIME" TIMESTAMP (6), 
	"FLOWTASKNAME" VARCHAR2(200 BYTE), 
	"FLOWINSTANCENAME" VARCHAR2(200 BYTE)
   );


  /*================================================*/
           /*TABLE XX_IMD_MODULES_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_MODULES_T" 
   (	"MODULE_ID" NUMBER, 
	"MODULE_CODE" VARCHAR2(20 BYTE), 
	"MODULE_NAME" VARCHAR2(200 BYTE), 
	"TRACK_CODE" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   );

  /*================================================*/
           /*TABLE XX_IMD_RECON_REPORT_DATA1*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_RECON_REPORT_DATA1$" 
   (	"ORA_ERR_NUMBER$" NUMBER, 
	"ORA_ERR_MESG$" VARCHAR2(2000 BYTE), 
	"ORA_ERR_ROWID$" UROWID (4000), 
	"ORA_ERR_OPTYP$" VARCHAR2(2 BYTE), 
	"ORA_ERR_TAG$" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(4000 BYTE), 
	"INTEGRATION_RUN_ID" VARCHAR2(4000 BYTE), 
	"RECORD_STATUS" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE11" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE12" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE13" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE14" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE15" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE16" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE17" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE18" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE19" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE20" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE21" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE22" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE23" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE24" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE25" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE26" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE27" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE28" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE29" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE30" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE31" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE32" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE33" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE34" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE35" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE36" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE37" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE38" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE39" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE40" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE41" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE42" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE43" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE44" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE45" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE46" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE47" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE48" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE49" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE50" VARCHAR2(4000 BYTE), 
	"CREATED_BY" VARCHAR2(4000 BYTE), 
	"CREATED_DATE" VARCHAR2(4000 BYTE), 
	"UPDATED_BY" VARCHAR2(4000 BYTE), 
	"UPDATED_DATE" VARCHAR2(4000 BYTE), 
	"INTEGRATION_ACTIVITY_ID" VARCHAR2(4000 BYTE), 
	"REQUEST_ID" VARCHAR2(4000 BYTE), 
	"ERROR_DESCRIPTION" VARCHAR2(4000 BYTE)
   );


  /*================================================*/
           /*TABLE XX_IMD_RECON_REPORT_DATA_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_RECON_REPORT_DATA_T" 
   (	"ID" NUMBER, 
	"INTEGRATION_RUN_ID" NUMBER, 
	"RECORD_STATUS" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE11" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE12" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE13" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE14" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE15" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE16" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE17" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE18" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE19" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE20" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE21" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE22" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE23" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE24" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE25" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE26" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE27" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE28" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE29" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE30" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE31" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE32" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE33" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE34" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE35" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE36" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE37" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE38" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE39" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE40" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE41" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE42" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE43" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE44" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE45" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE46" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE47" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE48" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE49" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE50" VARCHAR2(1000 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE), 
	"UPDATED_DATE" DATE, 
	"INTEGRATION_ACTIVITY_ID" NUMBER, 
	"REQUEST_ID" VARCHAR2(200 BYTE), 
	"ERROR_DESCRIPTION" VARCHAR2(3000 BYTE)
   );


  /*================================================*/
           /*TABLE XX_IMD_RECON_REPORT_HEADER_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_RECON_REPORT_HEADER_T" 
   (	"ID" NUMBER, 
	"INTEGRATION_RUN_ID" NUMBER, 
	"RECORD_STATUS" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE11" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE12" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE13" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE14" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE15" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE16" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE17" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE18" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE19" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE20" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE21" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE22" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE23" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE24" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE25" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE26" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE27" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE28" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE29" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE30" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE31" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE32" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE33" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE34" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE35" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE36" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE37" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE38" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE39" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE40" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE41" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE42" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE43" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE44" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE45" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE46" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE47" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE48" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE49" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE50" VARCHAR2(1000 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE), 
	"UPDATED_DATE" DATE, 
	"INTEGRATION_ACTIVITY_ID" NUMBER, 
	"INTEGRATION_MASTER_ID" NUMBER
   );

  /*================================================*/
           /*TABLE XX_IMD_RECON_REPORT_MASTER_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_RECON_REPORT_MASTER_T" 
   (	"ID" NUMBER, 
	"INTEGRATION_MASTER_ID" NUMBER, 
	"QUERY" CLOB, 
	"QUERY1" CLOB, 
	"QUERY2" CLOB
   );
   
  /*================================================*/
           /*TABLE XX_IMD_ROLE_MAPPINGS_T*/
  /*================================================*/
   CREATE TABLE "DGTL_PLS"."XX_IMD_ROLE_MAPPINGS_T" 
   (	"ID" NUMBER, 
	"ROLE" VARCHAR2(2000 BYTE), 
	"ACCESS_LEVEL" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE)
   );
   
   /*================================================*/
           /*INSERT SCRIPT XX_IMD_ROLE_MAPPINGS_T*/
   /*================================================*/
   INSERT INTO XX_IMD_ROLE_MAPPINGS_T (ID,ROLE,ACCESS_LEVEL,NAME) VALUES ('1','WSC_FINANCIALS_DIGITAL_PULSE_JR',NULL,NULL);


  /*================================================*/
           /*TABLE XX_IMD_SAAS_RECON_DTLS_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_SAAS_RECON_DTLS_T" 
   (	"RECON_ID" NUMBER, 
	"CALLBACK_ID" NUMBER, 
	"INTG_CODE" VARCHAR2(30 BYTE), 
	"RECON_DATA" CLOB, 
	"OAIC_INT_NAME" VARCHAR2(60 BYTE), 
	"SOURCE_FILE_NAME" VARCHAR2(240 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE), 
	"RUN_STATUS" VARCHAR2(10 BYTE)
   );


  /*================================================*/
           /*TABLE XX_IMD_SYSTEM_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_SYSTEM_T" 
   (	"SYS_ID" NUMBER, 
	"SYSTEM_CODE" VARCHAR2(20 BYTE), 
	"SYSTEM_NAME" VARCHAR2(200 BYTE), 
	"SYSTEM_DESC" VARCHAR2(400 BYTE), 
	"SYSTEM_ADD_DETAILS" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   );

  /*================================================*/
           /*TABLE XX_IMD_TRACKS_T*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_IMD_TRACKS_T" 
   (	"TRACK_ID" NUMBER, 
	"TRACK_CODE" VARCHAR2(20 BYTE), 
	"TRACK_NAME" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   );


  /*================================================*/
           /*TABLE XX_IMD_USER_ROLE_DETAILS_T*/
  /*================================================*/
CREATE TABLE "DGTL_PLS"."XX_IMD_USER_ROLE_DETAILS_T" 
   (	"USERNAME" VARCHAR2(2000 BYTE), 
	"ROLE" VARCHAR2(2000 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(2000 BYTE), 
	"FULL_NAME" VARCHAR2(2000 BYTE)
   );


  /*================================================*/
           /*TABLE XX_INTERACTIVE_TRANS_TBL*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_INTERACTIVE_TRANS_TBL" 
   (	"INTERFACE" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM" VARCHAR2(100 BYTE), 
	"DEST_SYSTEM" VARCHAR2(100 BYTE), 
	"PROGRAM_NAME" VARCHAR2(100 BYTE), 
	"ERROR_TRANSACTIONS" VARCHAR2(100 BYTE), 
	"UNPROCESSED_TRANSACTIONS" VARCHAR2(100 BYTE)
   );


  /*================================================*/
           /*TABLE XX_INTERM_JOB_PARAMETER*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_INTERM_JOB_PARAMETER" 
   (	"NAME" VARCHAR2(1000 BYTE), 
	"VALUE" VARCHAR2(1000 BYTE), 
	"REQUESTID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(1000 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(1000 BYTE), 
	"PARENT_JOB_SEQ" NUMBER
   );

  /*================================================*/
           /*TABLE XX_INTERM_PARAMETER*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_INTERM_PARAMETER" 
   (	"XML_OUTPUT" "SYS"."XMLTYPE" 
   ) ;

  /*================================================*/
           /*TABLE XX_INTERM_XML_OUTPUT*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_INTERM_XML_OUTPUT" 
   (	"XML_OUTPUT" "XMLTYPE"
   );
   
  /*================================================*/
           /*TABLE XX_SOAP_SERVICE_DATA*/
  /*================================================*/
 CREATE TABLE "DGTL_PLS"."XX_SOAP_SERVICE_DATA" 
   (	"REQUESTID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"DEFINITION" VARCHAR2(100 BYTE)
   )  ;
   
   /*================================================*/
       /*ALTER TABLE XX_IMD_INTEGRATION_RUN_T*/
  /*================================================*/
    ALTER TABLE  "XX_IMD_INTEGRATION_RUN_T" ADD CONSTRAINT "XX_IMD_INTEGRATION_RUN_T_FK" FOREIGN KEY ("INTEGRATION_MASTER_ID")
	  REFERENCES  "XX_IMD_INTEGRATION_MASTER_T" ("ID") ON DELETE SET NULL ENABLE; 
   
    /*================================================*/
       /*ALTER TABLE XX_IMD_INTEGRATION_ACTIVITY_T*/
  /*================================================*/
  ALTER TABLE  "XX_IMD_INTEGRATION_ACTIVITY_T" ADD CONSTRAINT "XX_IMD_INTEG_ACTIVITY_T_FK" FOREIGN KEY ("INTEGRATION_RUN_ID")
	  REFERENCES  "XX_IMD_INTEGRATION_RUN_T" ("ID") ON DELETE SET NULL ENABLE ;

  