Insert into xx_imd_tracks_t (TRACK_ID,TRACK_CODE,TRACK_NAME,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY) values (null,'ATR','Acquire to Retire',null,null,null,null);

commit;

Insert into xx_imd_system_t (SYS_ID,SYSTEM_CODE,SYSTEM_NAME,SYSTEM_DESC,SYSTEM_ADD_DETAILS,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY) values (null,'EBSAPFA','EBSAPFA',null,null,null,null,null,null);

commit;


Insert into xx_imd_modules_t (MODULE_ID,MODULE_CODE,MODULE_NAME,TRACK_CODE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY) values (null,'FA','Fixed Assets','ATR',null,null,null,null);

commit;

Insert into xx_imd_integration_master_t (ID,INTEGRATION_CODE,INTEGRATION_TYPE,RICE_CODE,DESCRIPTION,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,TRACK,SOURCE_SYSTEM,TARGET_SYSTEM,MODULE_CODE,JOB_ID,INTEGRATION_NAME) values (null,'INT245','INBOUND','INT245','EBSAPFA',null,null,null,null,'ATR','EBSAPFA','ORACLE_CLOUD','FA',null,'Oracle EBS AP to FA Integration');

commit;

Insert into xx_imd_integration_master_t (ID,INTEGRATION_CODE,INTEGRATION_TYPE,RICE_CODE,DESCRIPTION,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,TRACK,SOURCE_SYSTEM,TARGET_SYSTEM,MODULE_CODE,JOB_ID,INTEGRATION_NAME) values (null,'MASTER_DATA_INT245','INBOUND','INT245','EBSAPFA',null,null,null,null,'ATR','EBSAPFA','ORACLE_CLOUD','FA',null,'Oracle EBS AP to FA Integration Master Data');

commit;