drop table  "FININT"."WSC_AHCS_TW_TXN_HEADER_T";
drop table  "FININT"."WSC_AHCS_TW_TXN_LINE_T";
drop table  "FININT"."WSC_AHCS_TW_TXN_TMP_T";
DROP SEQUENCE "FININT"."WSC_TW_HEADER_T_S1"; 
DROP SEQUENCE "FININT"."WSC_TW_LINE_T_S1"; 
DROP SEQUENCE "FININT"."WSC_TW_TMP_LINE_NBR_S1"; 
DROP TYPE WSC_AHCS_TW_TXN_TMP_T_TYPE_TABLE;
DROP TYPE WSC_AHCS_TW_TXN_TMP_T_TYPE;