--------------------------------------------------------
--  DDL for Table WSC_AHCS_TW_TXN_HEADER_T
--------------------------------------------------------

  CREATE TABLE "FININT"."WSC_AHCS_TW_TXN_HEADER_T" 
   (	"BATCH_ID" NUMBER, 
	"HEADER_ID" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(30 BYTE), 
	"TRANSACTION_DATE" DATE, 
	"TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"LEDGER_NAME" VARCHAR2(20 BYTE), 
	"LEG_BUS_UNIT" VARCHAR2(20 BYTE), 
	"FILE_NAME" VARCHAR2(70 BYTE), 
	"SOURCE" VARCHAR2(10 BYTE), 
	"TRANS_REF_NBR" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" NUMBER, 
	"ATTRIBUTE11" NUMBER, 
	"ATTRIBUTE12" NUMBER, 
	"ATTRIBUTE6" DATE, 
	"ATTRIBUTE7" DATE, 
	"ATTRIBUTE1" VARCHAR2(240 BYTE), 
	"ATTRIBUTE2" VARCHAR2(240 BYTE), 
	"ATTRIBUTE3" VARCHAR2(240 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE),
   CONSTRAINT "WSC_AHCS_TW_TXN_HDR_T_PK" PRIMARY KEY ("HEADER_ID"));
   

--------------------------------------------------------
--  DDL for Table WSC_AHCS_TW_TXN_LINE_T
--------------------------------------------------------

  
  CREATE TABLE "FININT"."WSC_AHCS_TW_TXN_LINE_T" 
   (	"BATCH_ID" NUMBER, 
	"LINE_ID" NUMBER, 
	"HEADER_ID" NUMBER, 
	"BUSINESS_UNIT" NUMBER, 
	"APPL_JRNL_ID" VARCHAR2(10 BYTE), 
	"AXE_TRANS_DT" DATE, 
	"AXE_LINE_NBR" NUMBER, 
	"ACCOUNTING_DT" VARCHAR2(10 BYTE), 
	"BUSINESS_UNIT_GL" NUMBER, 
	"LEDGER" VARCHAR2(10 BYTE), 
	"LEDGER_GROUP" VARCHAR2(10 BYTE), 
	"ACCOUNT" NUMBER, 
	"ALTACCT" VARCHAR2(9 BYTE), 
	"AXE_LOC" VARCHAR2(5 BYTE), 
	"DEPTID" VARCHAR2(4 BYTE), 
	"PRODUCT" VARCHAR2(5 BYTE), 
	"AXE_MRKT_CHNL" VARCHAR2(2 BYTE), 
	"AXE_PROJECT" VARCHAR2(7 BYTE), 
	"PROJECT_ID" VARCHAR2(15 BYTE), 
	"AXE_VENDOR_10" VARCHAR2(10 BYTE), 
	"AFFILIATE" VARCHAR2(5 BYTE), 
	"MONETARY_AMOUNT" NUMBER, 
	"FOREIGN_AMOUNT" NUMBER, 
	"CURRENCY_CD" VARCHAR2(3 BYTE), 
	"FOREIGN_CURRENCY" VARCHAR2(3 BYTE), 
	"GL_DISTRIB_STATUS" VARCHAR2(1 BYTE), 
	"TRANS_REF_NBR" VARCHAR2(8 BYTE), 
	"DESCR" VARCHAR2(30 BYTE), 
	"SOURCE" VARCHAR2(3 BYTE), 
	"FILLER" VARCHAR2(101 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"LEG_BU" VARCHAR2(10 BYTE), 
	"LEG_ACCT" VARCHAR2(10 BYTE), 
	"LEG_DEPT" VARCHAR2(10 BYTE), 
	"LEG_LOC" VARCHAR2(10 BYTE), 
	"LEG_VENDOR" VARCHAR2(10 BYTE), 
	"LEG_AFFILIATE" VARCHAR2(10 BYTE), 
	"GL_LEGAL_ENTITY" VARCHAR2(20 BYTE), 
	"GL_OPER_GRP" VARCHAR2(20 BYTE), 
	"GL_ACCT" VARCHAR2(20 BYTE), 
	"GL_DEPT" VARCHAR2(20 BYTE), 
	"GL_SITE" VARCHAR2(20 BYTE), 
	"GL_IC" VARCHAR2(20 BYTE), 
	"GL_PROJECTS" VARCHAR2(20 BYTE), 
	"GL_FUT_1" VARCHAR2(20 BYTE), 
	"GL_FUT_2" VARCHAR2(20 BYTE), 
	"LEG_COA" VARCHAR2(100 BYTE), 
	"LEG_SEG_1_4" VARCHAR2(100 BYTE), 
	"LEG_SEG_5_7" VARCHAR2(100 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" NUMBER, 
	"ATTRIBUTE11" NUMBER, 
	"ATTRIBUTE12" NUMBER, 
	"ATTRIBUTE6" DATE, 
	"ATTRIBUTE7" DATE, 
	"ATTRIBUTE1" VARCHAR2(240 BYTE), 
	"ATTRIBUTE2" VARCHAR2(240 BYTE), 
	"ATTRIBUTE3" VARCHAR2(240 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"TARGET_COA" VARCHAR2(100 BYTE), 
	"LINE_NBR" NUMBER,
	CONSTRAINT "WSC_AHCS_TW_TXN_LINE_T_PK" PRIMARY KEY ("LINE_ID") );
   
   
--------------------------------------------------------
--  DDL for Table WSC_AHCS_TW_TXN_TMP_T
--------------------------------------------------------

 CREATE TABLE "FININT"."WSC_AHCS_TW_TXN_TMP_T" 
   (	"BATCH_ID" NUMBER, 
	"DATA_STRING" VARCHAR2(2000 BYTE), 
	"LINE_NBR" NUMBER
   );
   
   
   COMMIT;