SET DEFINE OFF;
----1A
PROMPT "EXECUTING WSC_AHCS_DASHBOARD_PKG.sql";
@WSC_AHCS_DASHBOARD_PKG.sql

PROMPT "EXECUTING WSC_AHCS_DASHBOARD_PKG_BODY.sql";
@WSC_AHCS_DASHBOARD_PKG_BODY.sql

PROMPT "EXECUTING WSC_AHCS_DASHBOARD1_V.sql";
@WSC_AHCS_DASHBOARD1_V.sql

PROMPT "EXECUTING WSC_COMMON_AHCS_PURGING_PKG_SPEC.sql";
@WSC_COMMON_AHCS_PURGING_PKG_SPEC.sql

PROMPT "EXECUTING WSC_COMMON_AHCS_PURGING_PKG_BODY.sql";
@WSC_COMMON_AHCS_PURGING_PKG_BODY.sql

PROMPT "EXECUTING WSC_UNIVERSAL_PKG.sql";
@WSC_UNIVERSAL_PKG.sql

PROMPT "EXECUTING WSC_UNIVERSAL_PKG_BODY.sql";
@WSC_UNIVERSAL_PKG_BODY.sql

PROMPT "EXECUTING WSC_AHCS_DASHBOARD1_DOWNLOAD_PROC.sql";
@WSC_AHCS_DASHBOARD1_DOWNLOAD_PROC.sql

PROMPT "EXECUTING WSC_COMMON_GRANT_JOB_SCHEDULER.sql";
@WSC_COMMON_GRANT_JOB_SCHEDULER.sql

PROMPT "EXECUTING DIGITALPULSE_XX_APEX_USER_SECURITY_PKG_SPEC.sql";
@DIGITALPULSE_XX_APEX_USER_SECURITY_PKG_SPEC.sql

PROMPT "EXECUTING DIGITALPULSE_XX_APEX_USER_SECURITY_PKG_BODY.sql";
@DIGITALPULSE_XX_APEX_USER_SECURITY_PKG_BODY.sql
----1B
@WSC_COMMON_insert.sql
@WSC_COMMON_GRANT_JOB_SCHEDULER.sql
@wsc_ahcs_mfstatus_tbl_update.sql
@WSC_AHCS_MFSTATUS_TBL_UPDATE_body.sql
@WSC_AHCS_DASHBOARD_PKG.sql
@WSC_AHCS_DASHBOARD_PKG_BODY.sql
@WSC_AHCS_DASHBOARD1_V.sql
@WSC_AHCS_REPROCESSING_PKG.sql
@WSC_AHCS_REPROCESSING_PKG_BODY.sql
@WSC_AHCS_INT_ERROR_LOGGING.sql
@WSC_AHCS_INT_ERROR_LOGGING_body.sql
@WSC_AHCS_PURGING_PKG.sql
@WSC_AHCS_PURGING_PKG_BODY.sql
@WSC_UNIVERSAL_PKG_BODY.sql
commit;

