--------------------------------------------------------
--  DDL for Index 
--------------------------------------------------------

CREATE INDEX "FININT"."WSC_AHCS_TW_TXN_HDR_BATCH_I" ON "FININT"."WSC_AHCS_TW_TXN_HEADER_T" ("BATCH_ID") ;
CREATE INDEX "FININT"."WSC_AHCS_TW_TXN_LINE_LEG_COA_I" ON "FININT"."WSC_AHCS_TW_TXN_LINE_T" ("LEG_COA") ;
CREATE INDEX "FININT"."WSC_AHCS_TW_TXN_LINE_HDR_ID_I" ON "FININT"."WSC_AHCS_TW_TXN_LINE_T" ("HEADER_ID") ;
CREATE INDEX "FININT"."WSC_AHCS_TW_TXN_LINE_BATCH_I" ON "FININT"."WSC_AHCS_TW_TXN_LINE_T" ("BATCH_ID") ;

ALTER INDEX WSC_AHCS_TW_TXN_HDR_BATCH_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_TW_TXN_LINE_LEG_COA_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_TW_TXN_LINE_HDR_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_TW_TXN_LINE_BATCH_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_TW_TXN_HDR_T_PK REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_TW_TXN_LINE_T_PK REBUILD COMPUTE STATISTICS;

commit;