SET DEFINE OFF;
Insert into WSC_GL_COA_MAPPING_RULES_T (RULE_ID,COA_MAP_ID,RULE_NAME,RULE_PRIORITY,SOURCE_SYSTEM,TARGET_SYSTEM,SOURCE_SEGMENT2,SOURCE_SEGMENT3,TARGET_SEGMENT,LAST_UPDATED_BY,LAST_UPDATE_DATE)
values (14,1,'WESCO - OpGroup - Based on Branch & Account',2,'Oracle EBS','Oracle ERP Cloud','Y','Y','segment2','FIN_INT',SYSDATE);
Commit;