SET ECHO ON;
SET DEFINE OFF;

PROMPT "EXECUTING WSC_EXTENSION_001_002_SEQUENCE.sql";
@WSC_EXTENSION_001_002_SEQUENCE.sql;

PROMPT "EXECUTING WSC_EXTENSION_001_002_TABLE.sql";
@WSC_EXTENSION_001_002_TABLE.sql;

PROMPT "EXECUTING WSC_EXTENSION_001_002_TABLE_INSERT.sql";
@WSC_EXTENSION_001_002_TABLE_INSERT.sql;

PROMPT "EXECUTING WSC_EXTENSION_001_002_INDEX.sql";
@WSC_EXTENSION_001_002_INDEX.sql;

PROMPT "EXECUTING WSC_GL_COA_INSERT_T.sql";
@WSC_GL_COA_INSERT_T.sql;

@Trigger_WSC_COA_SEGMENT_VALUE_AIR.sql;
@Insert_WSC_GL_COA_MAPPING_RULES_T.sql;
@Update_WSC_GL_COA_MAPPING_RULES_T.sql;

PROMPT "EXECUTING WSC_GL_COA_MAPPING_PKG.sql";
@WSC_GL_COA_MAPPING_PKG.sql;

PROMPT "EXECUTING WSC_GL_COA_MAPPING_PKG_BODY.sql";
@WSC_GL_COA_MAPPING_PKG_BODY.sql;

COMMIT;



