set define off;
--------------------------------------------------------
--1. Indexes for Table WSC_GL_COA_MAP_T
--------------------------------------------------------
  CREATE INDEX "FININT"."WSC_GL_COA_MAP_COA_NAME_I" ON "FININT"."WSC_GL_COA_MAP_T" ("COA_MAP_NAME") COMPUTE STATISTICS;

--------------------------------------------------------
--2. Indexes for Table WSC_GL_COA_MAPPING_RULES_T
--------------------------------------------------------
  CREATE INDEX "FININT"."WSC_GL_COA_MAPPING_RULE_COA_MAP_ID_I" ON "FININT"."WSC_GL_COA_MAPPING_RULES_T" ("COA_MAP_ID") COMPUTE STATISTICS;

  CREATE INDEX "FININT"."WSC_GL_COA_MPNG_RULES_RULE_ID_I" ON "FININT"."WSC_GL_COA_MAPPING_RULES_T" ("RULE_ID") COMPUTE STATISTICS;

  CREATE INDEX "FININT"."WSC_GL_COA_MPNG_RULES_RULE_NAME_I" ON "FININT"."WSC_GL_COA_MAPPING_RULES_T" ("RULE_NAME") COMPUTE STATISTICS;

  CREATE INDEX "FININT"."WSC_GL_COA_MPNG_RULES_TAR_SEG_I" ON "FININT"."WSC_GL_COA_MAPPING_RULES_T" ("TARGET_SEGMENT") COMPUTE STATISTICS;

--------------------------------------------------------
--3. Indexes for Table WSC_GL_COA_SEGMENT_VALUE_T
--------------------------------------------------------
  CREATE INDEX "FININT"."WSC_COA_SEGMENT_VALUE_SS_I" ON "FININT"."WSC_GL_COA_SEGMENT_VALUE_T" ("SOURCE_SEGMENT1", 
  "SOURCE_SEGMENT2", "SOURCE_SEGMENT3", "SOURCE_SEGMENT4", "SOURCE_SEGMENT5", "SOURCE_SEGMENT6", "SOURCE_SEGMENT7",
  "SOURCE_SEGMENT8", "SOURCE_SEGMENT9", "SOURCE_SEGMENT10") COMPUTE STATISTICS;

  CREATE INDEX "FININT"."WSC_GL_COA_MPNG_VALUE_RULE_ID_I" ON "FININT"."WSC_GL_COA_SEGMENT_VALUE_T" ("RULE_ID") COMPUTE STATISTICS;
 
  alter table WSC_GL_COA_SEGMENT_VALUE_T 
  add CONSTRAINT "WSC_GL_COA_SEG_VAL_CONS" 
  UNIQUE ("RULE_ID", "SOURCE_SEGMENT1", "SOURCE_SEGMENT2", "SOURCE_SEGMENT3", "SOURCE_SEGMENT4", "SOURCE_SEGMENT5", "SOURCE_SEGMENT6", 
  "SOURCE_SEGMENT7", "SOURCE_SEGMENT8", "SOURCE_SEGMENT9", "SOURCE_SEGMENT10", "VERSION", "FLAG");

--------------------------------------------------------
--4. Indexes for Table WSC_GL_CCID_MAPPING_T
--------------------------------------------------------
  CREATE INDEX "FININT"."WSC_GL_CCID_MPNG_COA_MAP_ID_I" ON "FININT"."WSC_GL_CCID_MAPPING_T" ("COA_MAP_ID") COMPUTE STATISTICS ;

  CREATE INDEX "FININT"."WSC_GL_CCID_MPNG_SRC_SEGS_I" ON "FININT"."WSC_GL_CCID_MAPPING_T" ("SOURCE_SEGMENT1", "SOURCE_SEGMENT2", 
  "SOURCE_SEGMENT3", "SOURCE_SEGMENT4", "SOURCE_SEGMENT5", "SOURCE_SEGMENT6", "SOURCE_SEGMENT7", "SOURCE_SEGMENT8", "SOURCE_SEGMENT9",
  "SOURCE_SEGMENT10") COMPUTE STATISTICS;

  CREATE INDEX "FININT"."WSC_GL_CCID_MPNG_SRC_SEG_I" ON "FININT"."WSC_GL_CCID_MAPPING_T" ("SOURCE_SEGMENT") COMPUTE STATISTICS ;
  
  alter table WSC_GL_CCID_MAPPING_T
  add CONSTRAINT "WSC_GL_CCID_MAPPING_CONS" 
  UNIQUE ("COA_MAP_ID", "SOURCE_SEGMENT", "VERSION", "ENABLE_FLAG");

--------------------------------------------------------
--5. Indexes for Table WSC_AHCS_COA_CONCAT_SEGMENT
--------------------------------------------------------
  CREATE INDEX "FININT"."COA_NAME_I" ON "FININT"."WSC_AHCS_COA_CONCAT_SEGMENT" ("COA_NAME") COMPUTE STATISTICS ;

  CREATE INDEX "FININT"."WSC_SEQ_NUM_I" ON "FININT"."WSC_AHCS_COA_CONCAT_SEGMENT" ("WSC_SEQ_NUM") COMPUTE STATISTICS ;