set define off;
--------------------------------------------------------
--1. Table WSC_GL_COA_MAP_T
--------------------------------------------------------
CREATE TABLE "FININT"."WSC_GL_COA_MAP_T" 
   (	"COA_MAP_ID" NUMBER, 
	"COA_MAP_NAME" VARCHAR2(100 BYTE), 
	"SOURCE_COA" VARCHAR2(100 BYTE), 
	"TARGET_COA" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM" VARCHAR2(100 BYTE), 
	"TARGET_SYSTEM" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_LOGIN" NUMBER,
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE)
   ) ;
  
--------------------------------------------------------
--2. Table WSC_GL_COA_SYSTEM_DEFINITIONS_T
--------------------------------------------------------

CREATE TABLE "FININT"."WSC_GL_COA_SYSTEM_DEFINITIONS_T" 
   (	"SYSTEM_ID" NUMBER, 
	"SYSTEM_NAME" VARCHAR2(200 BYTE), 
	"SOURCE_FLAG" VARCHAR2(10 BYTE), 
	"TARGET_FLAG" VARCHAR2(10 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ENABLED_FLAG" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
    "CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_LOGIN" NUMBER,
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE)	
   ) ;

--------------------------------------------------------
--3. Table WSC_GL_COA_SEGMENT_DEFINITIONS_T
--------------------------------------------------------

  CREATE TABLE "FININT"."WSC_GL_COA_SEGMENT_DEFINITIONS_T" 
   (	"SEGMENT_ID" NUMBER, 
	"SYSTEM_NAME" VARCHAR2(200 BYTE), 
	"SEGMENT_NAME" VARCHAR2(500 BYTE), 
	"SEGMENT_DESC" VARCHAR2(500 BYTE), 
	"SOURCE_FLAG" VARCHAR2(10 BYTE), 
	"TARGET_FLAG" VARCHAR2(10 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ENABLED_FLAG" VARCHAR2(20 BYTE), 
	"DISPLAY_SEQUENCE" NUMBER, 
	"SEGMENT_LENGTH" NUMBER, 
	"DEFAULT_VALUE" VARCHAR2(100 BYTE), 
    "CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_LOGIN" NUMBER,
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE)
   );

--------------------------------------------------------
--4. Table WSC_GL_COA_MAPPING_RULES_T
--------------------------------------------------------

  CREATE TABLE "FININT"."WSC_GL_COA_MAPPING_RULES_T" 
   (	"RULE_ID" NUMBER, 
	"COA_MAP_ID" NUMBER, 
	"RULE_NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"RULE_PRIORITY" NUMBER(10,0), 
	"SOURCE_SYSTEM" VARCHAR2(200 BYTE), 
	"TARGET_SYSTEM" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT1" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT2" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT3" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT4" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT5" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT6" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT7" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT8" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT9" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT10" VARCHAR2(200 BYTE), 
	"TARGET_SEGMENT" VARCHAR2(200 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(200 BYTE), 
    "CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_LOGIN" NUMBER,
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE)
   );

--------------------------------------------------------
--5. Table WSC_GL_COA_SEGMENT_VALUE_T
--------------------------------------------------------

CREATE TABLE "FININT"."WSC_GL_COA_SEGMENT_VALUE_T" 
   (	"RULE_ID" NUMBER, 
	"RULE_NAME" VARCHAR2(100 BYTE), 
	"VALUE_ID" NUMBER, 
	"SOURCE_SEGMENT1" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT2" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT3" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT4" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT5" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT6" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT7" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT8" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT9" VARCHAR2(200 BYTE), 
	"SOURCE_SEGMENT10" VARCHAR2(200 BYTE), 
	"TARGET_SEGMENT" VARCHAR2(200 BYTE), 
	"FLAG" VARCHAR2(10 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"VERSION" NUMBER DEFAULT 1,
    "CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_LOGIN" NUMBER	,
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE) 
	);

--------------------------------------------------------
--6. Table WSC_GL_CCID_MAPPING_T
--------------------------------------------------------

  CREATE TABLE "FININT"."WSC_GL_CCID_MAPPING_T" 
   (	"COA_MAP_ID" NUMBER, 
	"ENABLE_FLAG" VARCHAR2(10 BYTE), 
	"SOURCE_SEGMENT" VARCHAR2(1000 BYTE), 
	"TARGET_SEGMENT" VARCHAR2(1000 BYTE),
	"COA_MAP_NAME" VARCHAR2(200 BYTE), 
	"USER_NAME" VARCHAR2(200 BYTE), 
	"CCID_VALUE_ID" NUMBER, 
	"UI_FLAG" VARCHAR2(5 BYTE), 
	"SOURCE_SEGMENT1" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT2" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT3" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT4" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT5" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT6" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT7" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT8" VARCHAR2(50 BYTE), 
	"SOURCE_SEGMENT9" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT10" VARCHAR2(20 BYTE), 
	"VERSION" NUMBER DEFAULT 1,
    "CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATED_LOGIN" NUMBER,
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE7" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE8" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE9" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE10" VARCHAR2(1000 BYTE) 
	);
 
--------------------------------------------------------
--7. Table WSC_AHCS_COA_CONCAT_SEGMENT
--------------------------------------------------------

CREATE TABLE "FININT"."WSC_AHCS_COA_CONCAT_SEGMENT" 
   (	"COA_NAME" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT1" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT2" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT3" VARCHAR2(15 BYTE), 
	"SOURCE_SEGMENT4" VARCHAR2(15 BYTE), 
	"SOURCE_SEGMENT5" VARCHAR2(15 BYTE), 
	"SOURCE_SEGMENT6" VARCHAR2(15 BYTE), 
	"SOURCE_SEGMENT7" VARCHAR2(15 BYTE), 
	"SOURCE_SEGMENT8" VARCHAR2(20 BYTE), 
	"SOURCE_SEGMENT9" VARCHAR2(15 BYTE), 
	"SOURCE_SEGMENT10" VARCHAR2(15 BYTE), 
	"WSC_SEQ" VARCHAR2(10 BYTE), 
	"TARGET_COA" VARCHAR2(80 BYTE), 
	"WSC_SEQ_NUM" NUMBER
   ) ;

--------------------------------------------------------
--8. Table WSC_TBL_TIME_T
--------------------------------------------------------

CREATE TABLE "FININT"."WSC_TBL_TIME_T" 
   (	"A" VARCHAR2(100 BYTE), 
	"B" TIMESTAMP (6), 
	"C" NUMBER
   );