SET ECHO ON;
SET DEFINE OFF;

@WSC_AHCS_COA_SYNC_EXECUTION_SEQUENCE.SQL;
@WSC_AHCS_COA_SYNC_EXECUTION_TABLE.SQL;
@WSC_AHCS_COA_SYNC_EXECUTION_TABLE_DATA.SQL;
@WSC_AHCS_COA_SYNC_EXECUTION_INDEX.SQL;
@WSC_AHCS_COA_SYNC_PKG_SPEC.sql;
@WSC_AHCS_COA_SYNC_PKG_BODY.sql;

COMMIT;



