-------------------------------------------------------------------------------
--WSC_AHCS_COA_SYNC_EXECUTION_BATCH_ID_SEQ
-------------------------------------------------------------------------------
   
   CREATE SEQUENCE  "FININT"."WSC_AHCS_COA_SYNC_EXECUTION_BATCH_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-------------------------------------------------------------------------------
--WSC_AHCS_COA_SYNC_EXECUTION_LINE_ID_SEQ
-------------------------------------------------------------------------------
   
   CREATE SEQUENCE  "FININT"."WSC_AHCS_COA_SYNC_EXECUTION_LINE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

