SET ECHO ON;
SET DEFINE OFF;


PROMPT "EXECUTING WSC_CENTRAL_033_038_OC3_TABLE.sql";
@WSC_CENTRAL_033_038_OC3_TABLE.sql

PROMPT "EXECUTING WSC_CENTRAL_033_038_OC3_INDEX.sql";
@WSC_CENTRAL_033_038_OC3_INDEX.sql

PROMPT "EXECUTING Insert_WSC_AHCS_CENTRAL_REV_ACC_MAP_T.sql";
@Insert_WSC_AHCS_CENTRAL_REV_ACC_MAP_T.sql

PROMPT "EXECUTING Insert_WSC_AHCS_CENTRAL_REV_BRANCH_MAP_T.sql";
@Insert_WSC_AHCS_CENTRAL_REV_BRANCH_MAP_T.sql

PROMPT "EXECUTING WSC_CENTRAL_033_038_OC3_VandT_PKG.sql";
@WSC_CENTRAL_033_038_OC3_VandT_PKG.sql

PROMPT "EXECUTING WSC_CENTRAL_033_038_OC3_VandT_PKG_BODY.sql";
@WSC_CENTRAL_033_038_OC3_VandT_PKG_BODY.sql

PROMPT "EXECUTING WSC_CENTRAL_033_038_OC3_CENT_PKG.sql";
@WSC_CENTRAL_033_038_OC3_CENT_PKG.sql

PROMPT "EXECUTING WSC_CENTRAL_033_038_OC3_CENT_PKG_BODY.sql";
@WSC_CENTRAL_033_038_OC3_CENT_PKG_BODY.sql



COMMIT;

