  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_HEADER_BATCH_ID_I" ON "FININT"."WSC_AHCS_MFINV_TXN_HEADER_T" ("BATCH_ID");
  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_HEADER_HDR_SEQ_NBR_I" ON "FININT"."WSC_AHCS_MFINV_TXN_HEADER_T" ("HDR_SEQ_NBR");
  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_HEADER_LEDGER_NAME_I" ON "FININT"."WSC_AHCS_MFINV_TXN_HEADER_T" ("LEDGER_NAME") ;
  
  --ALTER TABLE "FININT"."WSC_AHCS_MFINV_TXN_HEADER_T" MODIFY ("HEADER_ID" NOT NULL ENABLE);
  --ALTER TABLE "FININT"."WSC_AHCS_MFINV_TXN_HEADER_T" ADD CONSTRAINT "WSC_AHCS_MFINV_TXN_HEADER_T_PK" PRIMARY KEY ("HEADER_ID");

  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_LINE_BATCH_ID_I" ON "FININT"."WSC_AHCS_MFINV_TXN_LINE_T" ("BATCH_ID");
  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_LINE_HDR_SEQ_NBR_I" ON "FININT"."WSC_AHCS_MFINV_TXN_LINE_T" ("HDR_SEQ_NBR"); 
  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_LINE_HEADER_ID_I" ON "FININT"."WSC_AHCS_MFINV_TXN_LINE_T" ("HEADER_ID");
  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_LINE_LEG_COA_I" ON "FININT"."WSC_AHCS_MFINV_TXN_LINE_T" ("LEG_COA") ;
  
  
  --ALTER TABLE "FININT"."WSC_AHCS_MFINV_TXN_LINE_T" MODIFY ("LINE_ID" NOT NULL ENABLE);
  ---ALTER TABLE "FININT"."WSC_AHCS_MFINV_TXN_LINE_T" ADD CONSTRAINT "WSC_AHCS_MFINV_TXN_LINE_T_PK" PRIMARY KEY ("LINE_ID");
  ---ALTER TABLE "FININT"."WSC_AHCS_MFINV_TXN_LINE_T" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);

  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TMP_T_REG_I" ON "FININT"."WSC_AHCS_MFINV_TXN_TMP_T" ( REGEXP_SUBSTR ("DATA_STRING",'([^|]*)(\||$)',1,1,NULL,1));
  CREATE INDEX "FININT"."WSC_AHCS_MFINV_TXN_TMP_BATCH_ID_I" ON "FININT"."WSC_AHCS_MFINV_TXN_TMP_T" ("BATCH_ID");
  
  commit;