REM INSERTING into FININT.wsc_gl_cao_map_t
SET DEFINE OFF;

insert into wsc_gl_coa_map_t(COA_MAP_ID,COA_MAP_NAME,SOURCE_COA,TARGET_COA,SOURCE_SYSTEM,TARGET_SYSTEM,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) values (6,'WESCO FA to Cloud','WESCO EBS FA COA','Cloud COA','Oracle EBS FA','Oracle ERP Cloud','FININT',SYSDATE,'FININT',SYSDATE);

commit;

REM INSERTING into FININT.WSC_GL_COA_MAPPING_RULES_T
SET DEFINE OFF;

insert into WSC_GL_COA_MAPPING_RULES_T(RULE_ID,COA_MAP_ID,RULE_NAME,RULE_PRIORITY,SOURCE_SYSTEM,TARGET_SYSTEM,SOURCE_SEGMENT2,TARGET_SEGMENT,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) values (300,6,'Wesco - FY25 Site based on Branch',1,'Oracle EBS FA','Oracle ERP Cloud','Y','segment5','FININT',SYSDATE,'FININT',SYSDATE);

commit;

insert into WSC_GL_COA_FY25_MAPPING_RULES_T(RULE_ID,COA_MAP_ID,RULE_NAME,RULE_PRIORITY,SOURCE_SYSTEM,TARGET_SYSTEM,SOURCE_SEGMENT2,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) values (300,6,'Wesco - FY25 Site based on Branch',1,'Oracle EBS FA','Oracle ERP Cloud','Y','FININT',SYSDATE,'FININT',SYSDATE);

commit;


