SET ECHO ON;
SET DEFINE OFF;

PROMPT "WSC_INT245_SEQUENCES.sql";
@WSC_INT245_SEQUENCES.sql

PROMPT "WSC_GEN_TABLES.sql";
@WSC_GEN_TABLES.sql

PROMPT "WSC_INT245_INDEXES.sql"
@WSC_INT245_INDEXES.sql

PROMPT "WSC_EBS_INT245_TABLE_TYPES.sql"
@WSC_EBS_INT245_TABLE_TYPES.sql

PROMPT "WSC_INT245_PROCEDURE.sql"
@WSC_INT245_PROCEDURE.sql

PROMPT "WSC_EBS_FA_PKG.sql"
@WSC_EBS_FA_PKG.sql

PROMPT "WSC_EBS_FA_PKG_BODY.sql"
@WSC_EBS_FA_PKG_BODY.sql

PROMPT "WSC_EBS_FA_VALIDATION_TRANSFORMATION_PKG.sql"
@WSC_EBS_FA_VALIDATION_TRANSFORMATION_PKG.sql

PROMPT "WSC_EBS_FA_VALIDATION_TRANSFORMATION_PKG_BODY.sql"
@WSC_EBS_FA_VALIDATION_TRANSFORMATION_PKG_BODY.sql

PROMPT "WSC_INT245_COA_DATA.sql"
@WSC_INT245_COA_DATA.sql

PROMPT "WSC_INT245_REFRESH.sql"
@WSC_INT245_REFRESH_T_ENTRY.sql

PROMPT "WSC_AHCS_PURGING_PKG_BODY.sql"
@WSC_AHCS_PURGING_PKG_BODY.sql

PROMPT "WSC_AHCS_INT_ERROR_LOGGING_BODY.sql"
@WSC_AHCS_INT_ERROR_LOGGING_BODY.sql
					   
COMMIT;