create or replace TYPE            "WSC_CRITICALJOBS_OUTPUT_T_TYPE"                                          force AS  OBJECT(
    EXECUTABLE_STATUS VARCHAR2(100),
	PROCESSEND VARCHAR2(100),   
	PROCESSSTART VARCHAR2(100),
	REQUESTEDSTART VARCHAR2(100),   
	DIFF_MINUTES VARCHAR2(100),   
	DEFINITION VARCHAR2(1000),    
	REQUESTID VARCHAR2(100),    
	SUBMITTER VARCHAR2(100),
	PROGRAMNAME VARCHAR2(1000),
	ATTRIBUTE1 VARCHAR2(100),
	ATTRIBUTE2 VARCHAR2(100)
);
/
create or replace TYPE            "WSC_CRITICALJOBS_OUTPUT_T_TAB"                                          AS TABLE OF WSC_CRITICALJOBS_OUTPUT_T_TYPE;
/

create or replace TYPE            "WSC_LONGRUNNINGJOBS_OUTPUT_T_TYPE"                                          force AS  OBJECT(
	EXECUTABLE_STATUS VARCHAR2(100),   
	PROCESSEND VARCHAR2(100),   
	PROCESSSTART VARCHAR2(100),   
	REQUESTEDSTART VARCHAR2(100),   
	DIFF_MINUTES VARCHAR2(100),   
	DEFINITION VARCHAR2(1000),    
	REQUESTID VARCHAR2(100),    
	SUBMITTER VARCHAR2(100), 
	PROGRAMNAME VARCHAR2(1000),				 
	ATTRIBUTE1 VARCHAR2(100),
	ATTRIBUTE2 VARCHAR2(100)
);
/
create or replace TYPE            "WSC_LONGRUNNINGJOBS_OUTPUT_T_TAB"                                          AS TABLE OF WSC_LONGRUNNINGJOBS_OUTPUT_T_TYPE;
/

create or replace TYPE            "WSC_OUTBOUNDJOBS_OUTPUT_T_TYPE"                                          force AS  OBJECT(
	EXECUTABLE_STATUS VARCHAR2(100),   
	PROCESSEND VARCHAR2(100),   
	PROCESSSTART VARCHAR2(100),   
	REQUESTEDSTART VARCHAR2(100),   
	DIFF_MINUTES VARCHAR2(100),   
	DEFINITION VARCHAR2(1000),    
	REQUESTID VARCHAR2(100),    
	SUBMITTER VARCHAR2(100),
	FLOWTASKNAME VARCHAR2(100),    
	FLOWINSTANCENAME VARCHAR2(100),    
	ERRORMSG VARCHAR2(100),
	PROGRAMNAME VARCHAR2(1000),				 
	ATTRIBUTE1 VARCHAR2(100),
	ATTRIBUTE2 VARCHAR2(100)
);
/
create or replace TYPE            "WSC_OUTBOUNDJOBS_OUTPUT_T_TAB"                                          AS TABLE OF WSC_OUTBOUNDJOBS_OUTPUT_T_TYPE;
/