SET ECHO ON;
SET DEFINE OFF;


PROMPT "EXECUTING WSC_GL_CCID_MAPPING_T_TABLE_BACKUP.sql";
@WSC_GL_CCID_MAPPING_T_TABLE_BACKUP.sql;

PROMPT "EXECUTING WSC_GL_COA_SEGMENT_VALUE_T_TABLE_BACKUP.sql";
@WSC_GL_COA_SEGMENT_VALUE_T_TABLE_BACKUP.sql;

PROMPT "EXECUTING WSC_GL_COA_MAPPING_RULES_T_TABLE_BACKUP.sql";
@WSC_GL_COA_MAPPING_RULES_T_TABLE_BACKUP.sql;

PROMPT "EXECUTING WSC_GL_CCID_MAPPING_T_TABLE_UPDATE.sql";
@WSC_GL_CCID_MAPPING_T_TABLE_UPDATE.sql;

PROMPT "EXECUTING WSC_GL_COA_SEGMENT_VALUE_T_TABLE_DELETE.sql";
@WSC_GL_COA_SEGMENT_VALUE_T_TABLE_DELETE.sql;

PROMPT "EXECUTING WSC_GL_COA_MAPPING_RULES_T_TABLE_DELETE.sql";
@WSC_GL_COA_MAPPING_RULES_T_TABLE_DELETE.sql;

COMMIT;
