

CREATE INDEX "FININT"."WSC_AHCS_PSFA_HEADER_BATCH_ID_I" ON "FININT"."WSC_AHCS_PSFA_TXN_HEADER_T" ("BATCH_ID");

CREATE INDEX "FININT"."WSC_AHCS_PSFA_HEADER_HDR_SEQ_NBR" ON "FININT"."WSC_AHCS_PSFA_TXN_HEADER_T" ("HDR_SEQ_NBR") ;

CREATE INDEX "FININT"."WSC_AHCS_PSFA_LINE_BATCH_ID_I" ON "FININT"."WSC_AHCS_PSFA_TXN_LINE_T" ("BATCH_ID") ;

CREATE INDEX "FININT"."WSC_AHCS_PSFA_LINE_HEADER_ID_I" ON "FININT"."WSC_AHCS_PSFA_TXN_LINE_T" ("HEADER_ID") ;

CREATE INDEX "FININT"."WSC_AHCS_PSFA_LINE_LEG_COA_I" ON "FININT"."WSC_AHCS_PSFA_TXN_LINE_T" ("LEG_COA") ;



ALTER INDEX WSC_AHCS_PSFA_HEADER_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_PSFA_HEADER_HDR_SEQ_NBR REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_PSFA_LINE_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_PSFA_LINE_HEADER_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_PSFA_LINE_LEG_COA_I REBUILD COMPUTE STATISTICS;
---ALTER INDEX WSC_AHCS_PSFA_TXN_HEADER_T_PK REBUILD COMPUTE STATISTICS;
--ALTER INDEX WSC_AHCS_PSFA_LINE_TXN_T_PK REBUILD COMPUTE STATISTICS;

COMMIT;