create or replace TYPE          "WSC_SXE_TMP_T_TYPE" FORCE AS OBJECT 
( 
"BATCH_ID" NUMBER, 
"RICE_ID" VARCHAR2(10 BYTE), 
"DATA_STRING" VARCHAR2(2000 BYTE),
"LINE_NUMBER" NUMBER
);
/


create or replace TYPE          "WSC_SXE_TMP_T_TYPE_TABLE" 
FORCE AS TABLE OF WSC_SXE_TMP_T_TYPE;
/
