--+========================================================================|
--| RICE_ID             : INT122 - Daily GL journal feed from ERP POC to AHCS
--| Module/Object Name  : WSC_POC_INDEX.sql
--|
--| Description         : Object to contain POC Table Indexes creation Script
--|
--| Creation Date       : 06-SEPT-2021
--|
--| Author              : Syed Zafer Ali
--|
--+========================================================================|
--| Modification History
--+========================================================================|
--| Date			Who					Version	    Change Description
--| -----------------------------------------------------------------------|
--| 06-SEPT-2021	Syed Zafer Ali   	Draft	    Initial draft version  |
--+========================================================================|

-- DROP INDEX WSC_AHCS_POC_TXN_HEADER_BATCH_ID_I;
-- DROP INDEX WSC_AHCS_POC_TXN_LINE_BATCH_ID_I;
-- DROP INDEX WSC_AHCS_POC_TXN_LINE_HEADER_ID_I;
-- DROP INDEX WSC_AHCS_POC_TXN_LINE_JE_HEADER_ID_I;
-- DROP INDEX WSC_AHCS_POC_TXN_HEADER_JE_HEADER_ID_I;
-- DROP INDEX WSC_AHCS_POC_TXN_LINE_LEG_COA_I;
-- /

CREATE INDEX "FININT"."WSC_AHCS_POC_TXN_HEADER_BATCH_ID_I" ON "FININT"."WSC_AHCS_POC_TXN_HEADER_T" ("BATCH_ID");
CREATE INDEX "FININT"."WSC_AHCS_POC_TXN_HEADER_JE_HEADER_ID_I" ON "FININT"."WSC_AHCS_POC_TXN_HEADER_T" ("JE_HEADER_ID");
CREATE INDEX "FININT"."WSC_AHCS_POC_TXN_LINE_BATCH_ID_I" ON "FININT"."WSC_AHCS_POC_TXN_LINE_T" ("BATCH_ID");
CREATE INDEX "FININT"."WSC_AHCS_POC_TXN_LINE_HEADER_ID_I" ON "FININT"."WSC_AHCS_POC_TXN_LINE_T" ("HEADER_ID");
CREATE INDEX "FININT"."WSC_AHCS_POC_TXN_LINE_JE_HEADER_ID_I" ON "FININT"."WSC_AHCS_POC_TXN_LINE_T" ("JE_HEADER_ID");
CREATE INDEX "FININT"."WSC_AHCS_POC_TXN_LINE_LEG_COA_I" ON "FININT"."WSC_AHCS_POC_TXN_LINE_T" ("LEG_COA");

ALTER INDEX WSC_AHCS_POC_TXN_HEADER_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_POC_TXN_HEADER_JE_HEADER_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_POC_TXN_HEADER_T_PK REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_POC_TXN_LINE_BATCH_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_POC_TXN_LINE_HEADER_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_POC_TXN_LINE_JE_HEADER_ID_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_POC_TXN_LINE_LEG_COA_I REBUILD COMPUTE STATISTICS;
ALTER INDEX WSC_AHCS_POC_TXN_LINE_T_PK REBUILD COMPUTE STATISTICS;