---------------------------------------------------
--WSC_USER_DATA_ACCESS_T
---------------------------------------------------

CREATE TABLE "FININT"."WSC_USER_DATA_ACCESS_T" 
(	"LEDGER_INTER_ORG_NAME" VARCHAR2(240 BYTE), 
	"LEDGER_INTER_ORG_ID" NUMBER, 
	"LEGAL_ENTITY_ID" NUMBER, 
	"ACTIVE_FLAG" VARCHAR2(2 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"ENTITY_TYPE" VARCHAR2(20 BYTE), 
	"COMPLETION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"ATTRIBUTE1" VARCHAR2(240 BYTE), 
	"ATTRIBUTE2" VARCHAR2(240 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" NUMBER, 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" DATE, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" VARCHAR2(240 BYTE)
);

---------------------------------------------------
--WSC_INTER_INTRA_COMPANY_FILE_HDR_T
---------------------------------------------------

CREATE TABLE "FININT"."WSC_INTER_INTRA_COMPANY_FILE_HDR_T" 
(	"BATCH_ID" NUMBER, 
	"PROVIDER" VARCHAR2(30 BYTE), 
	"IC_TRANSACTION_TYPE" VARCHAR2(30 BYTE), 
	"IC_BATCH_DATE" DATE, 
	"ACCOUNTING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(200 BYTE), 
	"JOURNAL_CATAGORY" VARCHAR2(50 BYTE), 
	"CONVERSION_RATE_TYPE" VARCHAR2(30 BYTE), 
	"FILE_NAME" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(1000 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"ATTRIBUTE1" NVARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" NUMBER, 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" DATE, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" VARCHAR2(240 BYTE), 
	"GL_IMPORT_ID" VARCHAR2(300 BYTE), 
	"IC_IMPORT_ID" NUMBER, 
	"IC_DOCUMENT_ID" NUMBER, 
	"GL_IMPORT_STATUS" VARCHAR2(200 BYTE), 
	"IC_IMPORT_STATUS" VARCHAR2(200 BYTE), 
	"GL_PROCESS_ID" VARCHAR2(300 BYTE), 
	"IC_PROCESS_ID" NUMBER, 
	"IC_GROUP_ID" NUMBER
);

---------------------------------------------------
--WSC_INTER_INTRA_COMPANY_FILE_LINE_T
---------------------------------------------------

CREATE TABLE "FININT"."WSC_INTER_INTRA_COMPANY_FILE_LINE_T" 
(	"BATCH_ID" NUMBER, 
	"LINE_ID" NUMBER, 
	"LE" VARCHAR2(20 BYTE), 
	"OP_GROUP" VARCHAR2(20 BYTE), 
	"ACCOUNT" VARCHAR2(20 BYTE), 
	"DEPT" VARCHAR2(20 BYTE), 
	"SITE" VARCHAR2(20 BYTE), 
	"IC" VARCHAR2(20 BYTE), 
	"PROJECT" VARCHAR2(20 BYTE), 
	"FUTURE1" VARCHAR2(20 BYTE), 
	"FUTURE2" VARCHAR2(20 BYTE), 
	"IC_PARTNER_IDENTIFIER" VARCHAR2(30 BYTE), 
	"TRANSACTION_CURRENCY" VARCHAR2(5 BYTE), 
	"ENTERED_DEBIT" NUMBER, 
	"ENTERED_CREDIT" NUMBER, 
	"ACCOUNTED_DEBIT" NUMBER, 
	"ACCOUNTED_CREDIT" NUMBER, 
	"LINE_DESCRIPTION" VARCHAR2(240 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(300 BYTE), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"ATTRIBUTE1" VARCHAR2(240 BYTE), 
	"ATTRIBUTE2" VARCHAR2(240 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" NUMBER, 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" DATE, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" VARCHAR2(240 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LEDGER_NAME" VARCHAR2(50 BYTE)
   );

---------------------------------------------------
--WSC_INTRA_GL_MAPPING_T
---------------------------------------------------

CREATE TABLE "FININT"."WSC_INTRA_GL_MAPPING_T" 
(	"BATCH_ID" NUMBER, 
	"LINE_ID" NUMBER, 
	"HEADER_ID" NUMBER, 
	"IMPORT_ID" NUMBER, 
	"IMPORT_STATUS" VARCHAR2(20 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(200 BYTE), 
	"JOURNAL_BATCH" VARCHAR2(100 BYTE), 
	"LEDGER_ID" VARCHAR2(18 BYTE), 
	"ACCOUNTING_DATE" DATE, 
	"JOURNAL_SOURCE" VARCHAR2(25 BYTE), 
	"JOURNAL_CATAGORY" VARCHAR2(25 BYTE), 
	"ENTERED_CURRENCY" VARCHAR2(15 BYTE), 
	"CONVERSION_RATE_TYPE" VARCHAR2(30 BYTE), 
	"GL_LE" VARCHAR2(20 BYTE), 
	"GL_OP_GROUP" VARCHAR2(20 BYTE), 
	"GL_ACCOUNT" VARCHAR2(20 BYTE), 
	"GL_DEPT" VARCHAR2(20 BYTE), 
	"GL_SITE" VARCHAR2(20 BYTE), 
	"GL_IC" VARCHAR2(20 BYTE), 
	"GL_PROJECT" VARCHAR2(20 BYTE), 
	"GL_FUTURE1" VARCHAR2(20 BYTE), 
	"GL_FUTURE2" VARCHAR2(20 BYTE), 
	"ENTERED_DEBIT" NUMBER, 
	"ENTERED_CREDIT" NUMBER, 
	"ACCOUNTED_DEBIT" NUMBER, 
	"ACCOUNTEED_CREDIT" NUMBER, 
	"LINE_DESCRIPTION" VARCHAR2(240 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"ATTRIBUTE1" NVARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" NUMBER, 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" DATE, 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" VARCHAR2(240 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PROCESS_ID" NUMBER
);

---------------------------------------------------
--WSC_INTER_IC_MAPPING_T
---------------------------------------------------

CREATE TABLE "FININT"."WSC_INTER_IC_MAPPING_T" 
(	"BATCH_ID" NUMBER, 
	"LINE_ID" NUMBER, 
	"HEADER_ID" NUMBER, 
	"IMPORT_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"IMPORT_STATUS" VARCHAR2(20 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(200 BYTE), 
	"PROVIDER_LE" VARCHAR2(360 BYTE), 
	"IC_TRX_TYPE" VARCHAR2(200 BYTE), 
	"IC_BATCH_DATE" DATE, 
	"ACCOUNTING_DATE" DATE, 
	"CONVERSION_RATE_TYPE" VARCHAR2(25 BYTE), 
	"TRANSACTION_CURRENCY" VARCHAR2(15 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"LE" VARCHAR2(20 BYTE), 
	"OP_GROUP" VARCHAR2(20 BYTE), 
	"ACCOUNT" VARCHAR2(20 BYTE), 
	"DEPT" VARCHAR2(20 BYTE), 
	"SITE" VARCHAR2(20 BYTE), 
	"IC" VARCHAR2(25 BYTE), 
	"PROJECT" VARCHAR2(20 BYTE), 
	"FUTURE1" VARCHAR2(20 BYTE), 
	"FUTURE2" VARCHAR2(20 BYTE), 
	"FILE_LEVEL_LINE_NUMBER" NUMBER, 
	"FILE_LINE_TYPE_CODE" VARCHAR2(5 BYTE), 
	"SOURCE_NAME" VARCHAR2(20 BYTE), 
	"TRANSACTION_LEVEL_LINE_NUMBER" VARCHAR2(20 BYTE), 
	"RECEIVER_LE_NAME" VARCHAR2(360 BYTE), 
	"TRANSACTION__LINE_TYPE_CODE" VARCHAR2(100 BYTE), 
	"ENTERED_DR" NUMBER, 
	"ENTERED_CR" NUMBER, 
	"BATCH_NOTES" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"ATTRIBUTE1" VARCHAR2(240 BYTE), 
	"ATTRIBUTE2" VARCHAR2(240 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" NUMBER, 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" NUMBER, 
	"ATTRIBUTE10" DATE, 
	"BATCH_NUMBER" VARCHAR2(15 BYTE), 
	"ATTRIBUTE11" DATE, 
	"ATTRIBUTE12" VARCHAR2(240 BYTE), 
	"IC_GROUP_ID" NUMBER
);

---------------------------------------------------
--WSC_INTER_INTRA_TEMPLATE_T
---------------------------------------------------

CREATE TABLE "FININT"."WSC_INTER_INTRA_TEMPLATE_T" 
(	"ID" NUMBER, 
	"BLOB_DATA" BLOB, 
	"MIME_TYPE" VARCHAR2(1000 BYTE)
);