create or replace Package WSC_USER_DATA_ACCESS_PKG IS 
	PROCEDURE INSERT_REC(P_INS_VAL WSC_USER_DATA_ACCESS_T_TAB,
		P_ERR_MSG OUT VARCHAR2,
		P_ERR_CODE OUT VARCHAR2
	);
END WSC_USER_DATA_ACCESS_PKG;
/