SET DEFINE OFF;
@WSC_INT123_HEADER_T_LINE_T_TMP_T.sql
@WSC_INT123_INDEXES.sql
@WSC_INT123_SEQUENCE.sql
@WSC_INT123_TABLE_TYPE.sql
@WSC_INT123_PKG.sql
@WSC_INT123_PKG_BODY.sql
@wsc_INT123_validation_transformation_pkg.sql
@WSC_INT123_VALIDATION_TRANSFORMATION_PKG_BODY.sql
commit;