REM INSERTING into WSC_AHCS_REFRESH_T
SET DEFINE OFF;
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (null,'DEV_URL',to_date('08-NOV-21','DD-MON-RR'),'xx05911','https://eklm-dev20.fa.us2.oraclecloud.com/xmlpserver');
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (null,'SIT1_URL',to_date('08-NOV-21','DD-MON-RR'),'xx05911','https://eklm-dev21.fa.us2.oraclecloud.com/xmlpserver');
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (null,'SIT2_URL',to_date('08-NOV-21','DD-MON-RR'),'xx05911','https://eklm-dev2.fa.us2.oraclecloud.com/xmlpserver');
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (null,'UAT2_URL',to_date('08-NOV-21','DD-MON-RR'),'xx05911','https://eklm-dev21.fa.us2.oraclecloud.com/xmlpserver');
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (to_timestamp('08-NOV-21 10.47.11.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'WSC_AHCS_DASHBOARD2_REFRESH',to_date('08-NOV-21','DD-MON-RR'),'Integration Program',null);
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (to_timestamp('08-NOV-21 10.18.53.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'WSC_AHCS_RECON_REPORT',to_date('08-NOV-21','DD-MON-RR'),'Integration Program',null);
Insert into WSC_AHCS_REFRESH_T (LAST_REFRESH_DATE,DATA_ENTITY_NAME,LAST_UPDATE_DATE,LAST_UPDATED_BY,VALUE) values (to_timestamp('03-NOV-21 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'WSC_COMMON_GL_LE_EXTRACT',to_date('03-NOV-21','DD-MON-RR'),'GL LE Extract Program',null);

Commit;
