SET ECHO ON;
SET DEFINE OFF;

@WSC_AHCS_TXN_PURGE_SEQUENCE.SQL;
@WSC_AHCS_TXN_PURGE_TABLE.SQL;
@WSC_TEMPLATE_DATA_INSERTION.sql;
@WSC_AHCS_TXN_PURGE_PKG_SPEC.SQL;
@WSC_AHCS_TXN_PURGE_PKG_BODY.SQL;
@WSC_AHCS_DASHBOARD_PKG_BODY.sql;

COMMIT;



